// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: smartcore/bos/info/v1/health.proto

package infopb

import (
	typespb "github.com/smart-core-os/sc-bos/pkg/proto/typespb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Health of the connection to the physical device
	Connection *ConnectionHealth `protobuf:"bytes,1,opt,name=connection,proto3" json:"connection,omitempty"`
	// Health of communication with the device
	Comm          *CommHealth `protobuf:"bytes,2,opt,name=comm,proto3" json:"comm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthState) Reset() {
	*x = HealthState{}
	mi := &file_smartcore_bos_info_v1_health_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthState) ProtoMessage() {}

func (x *HealthState) ProtoReflect() protoreflect.Message {
	mi := &file_smartcore_bos_info_v1_health_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthState.ProtoReflect.Descriptor instead.
func (*HealthState) Descriptor() ([]byte, []int) {
	return file_smartcore_bos_info_v1_health_proto_rawDescGZIP(), []int{0}
}

func (x *HealthState) GetConnection() *ConnectionHealth {
	if x != nil {
		return x.Connection
	}
	return nil
}

func (x *HealthState) GetComm() *CommHealth {
	if x != nil {
		return x.Comm
	}
	return nil
}

// Describes the health of a connection
type ConnectionHealth struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// are we currently connected
	Status typespb.Connectivity `protobuf:"varint,1,opt,name=status,proto3,enum=smartcore.bos.types.v1.Connectivity" json:"status,omitempty"`
	// When was the last time a successful connection was established
	ConnectTime *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=connect_time,json=connectTime,proto3" json:"connect_time,omitempty"`
	// When was the last time a connection was closed/ended
	DisconnectTime *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=disconnect_time,json=disconnectTime,proto3" json:"disconnect_time,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ConnectionHealth) Reset() {
	*x = ConnectionHealth{}
	mi := &file_smartcore_bos_info_v1_health_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionHealth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionHealth) ProtoMessage() {}

func (x *ConnectionHealth) ProtoReflect() protoreflect.Message {
	mi := &file_smartcore_bos_info_v1_health_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionHealth.ProtoReflect.Descriptor instead.
func (*ConnectionHealth) Descriptor() ([]byte, []int) {
	return file_smartcore_bos_info_v1_health_proto_rawDescGZIP(), []int{1}
}

func (x *ConnectionHealth) GetStatus() typespb.Connectivity {
	if x != nil {
		return x.Status
	}
	return typespb.Connectivity(0)
}

func (x *ConnectionHealth) GetConnectTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ConnectTime
	}
	return nil
}

func (x *ConnectionHealth) GetDisconnectTime() *timestamppb.Timestamp {
	if x != nil {
		return x.DisconnectTime
	}
	return nil
}

// Describes the health of communication.
type CommHealth struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Status typespb.CommStatus     `protobuf:"varint,1,opt,name=status,proto3,enum=smartcore.bos.types.v1.CommStatus" json:"status,omitempty"`
	// The most recent time the status changed to COMM_FAILURE
	FailureTime *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=failure_time,json=failureTime,proto3" json:"failure_time,omitempty"`
	// The most recent time the status changed to COMM_SUCCESS
	SuccessTime   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=success_time,json=successTime,proto3" json:"success_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommHealth) Reset() {
	*x = CommHealth{}
	mi := &file_smartcore_bos_info_v1_health_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommHealth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommHealth) ProtoMessage() {}

func (x *CommHealth) ProtoReflect() protoreflect.Message {
	mi := &file_smartcore_bos_info_v1_health_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommHealth.ProtoReflect.Descriptor instead.
func (*CommHealth) Descriptor() ([]byte, []int) {
	return file_smartcore_bos_info_v1_health_proto_rawDescGZIP(), []int{2}
}

func (x *CommHealth) GetStatus() typespb.CommStatus {
	if x != nil {
		return x.Status
	}
	return typespb.CommStatus(0)
}

func (x *CommHealth) GetFailureTime() *timestamppb.Timestamp {
	if x != nil {
		return x.FailureTime
	}
	return nil
}

func (x *CommHealth) GetSuccessTime() *timestamppb.Timestamp {
	if x != nil {
		return x.SuccessTime
	}
	return nil
}

type GetHealthStateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the device to query the health state for
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHealthStateRequest) Reset() {
	*x = GetHealthStateRequest{}
	mi := &file_smartcore_bos_info_v1_health_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHealthStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHealthStateRequest) ProtoMessage() {}

func (x *GetHealthStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_smartcore_bos_info_v1_health_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHealthStateRequest.ProtoReflect.Descriptor instead.
func (*GetHealthStateRequest) Descriptor() ([]byte, []int) {
	return file_smartcore_bos_info_v1_health_proto_rawDescGZIP(), []int{3}
}

func (x *GetHealthStateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type PullHealthStatesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the device to subscribe to the health state for
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullHealthStatesRequest) Reset() {
	*x = PullHealthStatesRequest{}
	mi := &file_smartcore_bos_info_v1_health_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullHealthStatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullHealthStatesRequest) ProtoMessage() {}

func (x *PullHealthStatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_smartcore_bos_info_v1_health_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullHealthStatesRequest.ProtoReflect.Descriptor instead.
func (*PullHealthStatesRequest) Descriptor() ([]byte, []int) {
	return file_smartcore_bos_info_v1_health_proto_rawDescGZIP(), []int{4}
}

func (x *PullHealthStatesRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type PullHealthStatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Changes       []*HealthStateChange   `protobuf:"bytes,1,rep,name=changes,proto3" json:"changes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullHealthStatesResponse) Reset() {
	*x = PullHealthStatesResponse{}
	mi := &file_smartcore_bos_info_v1_health_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullHealthStatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullHealthStatesResponse) ProtoMessage() {}

func (x *PullHealthStatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_smartcore_bos_info_v1_health_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullHealthStatesResponse.ProtoReflect.Descriptor instead.
func (*PullHealthStatesResponse) Descriptor() ([]byte, []int) {
	return file_smartcore_bos_info_v1_health_proto_rawDescGZIP(), []int{5}
}

func (x *PullHealthStatesResponse) GetChanges() []*HealthStateChange {
	if x != nil {
		return x.Changes
	}
	return nil
}

type HealthStateChange struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the device that is the source of the change
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// When the change was applied
	ChangeTime *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=change_time,json=changeTime,proto3" json:"change_time,omitempty"`
	// The new state for the change
	Health        *HealthState `protobuf:"bytes,3,opt,name=health,proto3" json:"health,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthStateChange) Reset() {
	*x = HealthStateChange{}
	mi := &file_smartcore_bos_info_v1_health_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthStateChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthStateChange) ProtoMessage() {}

func (x *HealthStateChange) ProtoReflect() protoreflect.Message {
	mi := &file_smartcore_bos_info_v1_health_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthStateChange.ProtoReflect.Descriptor instead.
func (*HealthStateChange) Descriptor() ([]byte, []int) {
	return file_smartcore_bos_info_v1_health_proto_rawDescGZIP(), []int{6}
}

func (x *HealthStateChange) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HealthStateChange) GetChangeTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ChangeTime
	}
	return nil
}

func (x *HealthStateChange) GetHealth() *HealthState {
	if x != nil {
		return x.Health
	}
	return nil
}

var File_smartcore_bos_info_v1_health_proto protoreflect.FileDescriptor

const file_smartcore_bos_info_v1_health_proto_rawDesc = "" +
	"\n" +
	"\"smartcore/bos/info/v1/health.proto\x12\x15smartcore.bos.info.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a'smartcore/bos/types/v1/connection.proto\"\x8d\x01\n" +
	"\vHealthState\x12G\n" +
	"\n" +
	"connection\x18\x01 \x01(\v2'.smartcore.bos.info.v1.ConnectionHealthR\n" +
	"connection\x125\n" +
	"\x04comm\x18\x02 \x01(\v2!.smartcore.bos.info.v1.CommHealthR\x04comm\"\xd4\x01\n" +
	"\x10ConnectionHealth\x12<\n" +
	"\x06status\x18\x01 \x01(\x0e2$.smartcore.bos.types.v1.ConnectivityR\x06status\x12=\n" +
	"\fconnect_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\vconnectTime\x12C\n" +
	"\x0fdisconnect_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x0edisconnectTime\"\xc6\x01\n" +
	"\n" +
	"CommHealth\x12:\n" +
	"\x06status\x18\x01 \x01(\x0e2\".smartcore.bos.types.v1.CommStatusR\x06status\x12=\n" +
	"\ffailure_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\vfailureTime\x12=\n" +
	"\fsuccess_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\vsuccessTime\"+\n" +
	"\x15GetHealthStateRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"-\n" +
	"\x17PullHealthStatesRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"^\n" +
	"\x18PullHealthStatesResponse\x12B\n" +
	"\achanges\x18\x01 \x03(\v2(.smartcore.bos.info.v1.HealthStateChangeR\achanges\"\xa0\x01\n" +
	"\x11HealthStateChange\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12;\n" +
	"\vchange_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"changeTime\x12:\n" +
	"\x06health\x18\x03 \x01(\v2\".smartcore.bos.info.v1.HealthStateR\x06health2\xe7\x01\n" +
	"\x06Health\x12d\n" +
	"\x0eGetHealthState\x12,.smartcore.bos.info.v1.GetHealthStateRequest\x1a\".smartcore.bos.info.v1.HealthState\"\x00\x12w\n" +
	"\x10PullHealthStates\x12..smartcore.bos.info.v1.PullHealthStatesRequest\x1a/.smartcore.bos.info.v1.PullHealthStatesResponse\"\x000\x01Bw\n" +
	"\x12dev.smartcore.infoB\vHealthProtoP\x01Z0github.com/smart-core-os/sc-bos/pkg/proto/infopb\xaa\x02\x0eSmartcore.Info\xca\x02\x0eSmartcore\\Infob\x06proto3"

var (
	file_smartcore_bos_info_v1_health_proto_rawDescOnce sync.Once
	file_smartcore_bos_info_v1_health_proto_rawDescData []byte
)

func file_smartcore_bos_info_v1_health_proto_rawDescGZIP() []byte {
	file_smartcore_bos_info_v1_health_proto_rawDescOnce.Do(func() {
		file_smartcore_bos_info_v1_health_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_smartcore_bos_info_v1_health_proto_rawDesc), len(file_smartcore_bos_info_v1_health_proto_rawDesc)))
	})
	return file_smartcore_bos_info_v1_health_proto_rawDescData
}

var file_smartcore_bos_info_v1_health_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_smartcore_bos_info_v1_health_proto_goTypes = []any{
	(*HealthState)(nil),              // 0: smartcore.bos.info.v1.HealthState
	(*ConnectionHealth)(nil),         // 1: smartcore.bos.info.v1.ConnectionHealth
	(*CommHealth)(nil),               // 2: smartcore.bos.info.v1.CommHealth
	(*GetHealthStateRequest)(nil),    // 3: smartcore.bos.info.v1.GetHealthStateRequest
	(*PullHealthStatesRequest)(nil),  // 4: smartcore.bos.info.v1.PullHealthStatesRequest
	(*PullHealthStatesResponse)(nil), // 5: smartcore.bos.info.v1.PullHealthStatesResponse
	(*HealthStateChange)(nil),        // 6: smartcore.bos.info.v1.HealthStateChange
	(typespb.Connectivity)(0),        // 7: smartcore.bos.types.v1.Connectivity
	(*timestamppb.Timestamp)(nil),    // 8: google.protobuf.Timestamp
	(typespb.CommStatus)(0),          // 9: smartcore.bos.types.v1.CommStatus
}
var file_smartcore_bos_info_v1_health_proto_depIdxs = []int32{
	1,  // 0: smartcore.bos.info.v1.HealthState.connection:type_name -> smartcore.bos.info.v1.ConnectionHealth
	2,  // 1: smartcore.bos.info.v1.HealthState.comm:type_name -> smartcore.bos.info.v1.CommHealth
	7,  // 2: smartcore.bos.info.v1.ConnectionHealth.status:type_name -> smartcore.bos.types.v1.Connectivity
	8,  // 3: smartcore.bos.info.v1.ConnectionHealth.connect_time:type_name -> google.protobuf.Timestamp
	8,  // 4: smartcore.bos.info.v1.ConnectionHealth.disconnect_time:type_name -> google.protobuf.Timestamp
	9,  // 5: smartcore.bos.info.v1.CommHealth.status:type_name -> smartcore.bos.types.v1.CommStatus
	8,  // 6: smartcore.bos.info.v1.CommHealth.failure_time:type_name -> google.protobuf.Timestamp
	8,  // 7: smartcore.bos.info.v1.CommHealth.success_time:type_name -> google.protobuf.Timestamp
	6,  // 8: smartcore.bos.info.v1.PullHealthStatesResponse.changes:type_name -> smartcore.bos.info.v1.HealthStateChange
	8,  // 9: smartcore.bos.info.v1.HealthStateChange.change_time:type_name -> google.protobuf.Timestamp
	0,  // 10: smartcore.bos.info.v1.HealthStateChange.health:type_name -> smartcore.bos.info.v1.HealthState
	3,  // 11: smartcore.bos.info.v1.Health.GetHealthState:input_type -> smartcore.bos.info.v1.GetHealthStateRequest
	4,  // 12: smartcore.bos.info.v1.Health.PullHealthStates:input_type -> smartcore.bos.info.v1.PullHealthStatesRequest
	0,  // 13: smartcore.bos.info.v1.Health.GetHealthState:output_type -> smartcore.bos.info.v1.HealthState
	5,  // 14: smartcore.bos.info.v1.Health.PullHealthStates:output_type -> smartcore.bos.info.v1.PullHealthStatesResponse
	13, // [13:15] is the sub-list for method output_type
	11, // [11:13] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_smartcore_bos_info_v1_health_proto_init() }
func file_smartcore_bos_info_v1_health_proto_init() {
	if File_smartcore_bos_info_v1_health_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_smartcore_bos_info_v1_health_proto_rawDesc), len(file_smartcore_bos_info_v1_health_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_smartcore_bos_info_v1_health_proto_goTypes,
		DependencyIndexes: file_smartcore_bos_info_v1_health_proto_depIdxs,
		MessageInfos:      file_smartcore_bos_info_v1_health_proto_msgTypes,
	}.Build()
	File_smartcore_bos_info_v1_health_proto = out.File
	file_smartcore_bos_info_v1_health_proto_goTypes = nil
	file_smartcore_bos_info_v1_health_proto_depIdxs = nil
}
