// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.34.0
// source: smartcore/bos/dataretention/v1/data_retention.proto

package dataretentionpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DataRetentionApi_GetDataRetention_FullMethodName     = "/smartcore.bos.dataretention.v1.DataRetentionApi/GetDataRetention"
	DataRetentionApi_PullDataRetention_FullMethodName    = "/smartcore.bos.dataretention.v1.DataRetentionApi/PullDataRetention"
	DataRetentionApi_PurgeDataRetention_FullMethodName   = "/smartcore.bos.dataretention.v1.DataRetentionApi/PurgeDataRetention"
	DataRetentionApi_CompactDataRetention_FullMethodName = "/smartcore.bos.dataretention.v1.DataRetentionApi/CompactDataRetention"
)

// DataRetentionApiClient is the client API for DataRetentionApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DataRetentionApi provides access to data retention utilisation stats and administrative actions.
type DataRetentionApiClient interface {
	GetDataRetention(ctx context.Context, in *GetDataRetentionRequest, opts ...grpc.CallOption) (*DataRetention, error)
	PullDataRetention(ctx context.Context, in *PullDataRetentionRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PullDataRetentionResponse], error)
	// Remove stored data. If before is set, only records older than that time are removed;
	// if absent, all records are removed.
	PurgeDataRetention(ctx context.Context, in *PurgeDataRetentionRequest, opts ...grpc.CallOption) (*PurgeDataRetentionResponse, error)
	// Compact/optimise storage (GC, VACUUM, repack).
	CompactDataRetention(ctx context.Context, in *CompactDataRetentionRequest, opts ...grpc.CallOption) (*CompactDataRetentionResponse, error)
}

type dataRetentionApiClient struct {
	cc grpc.ClientConnInterface
}

func NewDataRetentionApiClient(cc grpc.ClientConnInterface) DataRetentionApiClient {
	return &dataRetentionApiClient{cc}
}

func (c *dataRetentionApiClient) GetDataRetention(ctx context.Context, in *GetDataRetentionRequest, opts ...grpc.CallOption) (*DataRetention, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DataRetention)
	err := c.cc.Invoke(ctx, DataRetentionApi_GetDataRetention_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataRetentionApiClient) PullDataRetention(ctx context.Context, in *PullDataRetentionRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PullDataRetentionResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DataRetentionApi_ServiceDesc.Streams[0], DataRetentionApi_PullDataRetention_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PullDataRetentionRequest, PullDataRetentionResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataRetentionApi_PullDataRetentionClient = grpc.ServerStreamingClient[PullDataRetentionResponse]

func (c *dataRetentionApiClient) PurgeDataRetention(ctx context.Context, in *PurgeDataRetentionRequest, opts ...grpc.CallOption) (*PurgeDataRetentionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PurgeDataRetentionResponse)
	err := c.cc.Invoke(ctx, DataRetentionApi_PurgeDataRetention_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataRetentionApiClient) CompactDataRetention(ctx context.Context, in *CompactDataRetentionRequest, opts ...grpc.CallOption) (*CompactDataRetentionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompactDataRetentionResponse)
	err := c.cc.Invoke(ctx, DataRetentionApi_CompactDataRetention_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataRetentionApiServer is the server API for DataRetentionApi service.
// All implementations must embed UnimplementedDataRetentionApiServer
// for forward compatibility.
//
// DataRetentionApi provides access to data retention utilisation stats and administrative actions.
type DataRetentionApiServer interface {
	GetDataRetention(context.Context, *GetDataRetentionRequest) (*DataRetention, error)
	PullDataRetention(*PullDataRetentionRequest, grpc.ServerStreamingServer[PullDataRetentionResponse]) error
	// Remove stored data. If before is set, only records older than that time are removed;
	// if absent, all records are removed.
	PurgeDataRetention(context.Context, *PurgeDataRetentionRequest) (*PurgeDataRetentionResponse, error)
	// Compact/optimise storage (GC, VACUUM, repack).
	CompactDataRetention(context.Context, *CompactDataRetentionRequest) (*CompactDataRetentionResponse, error)
	mustEmbedUnimplementedDataRetentionApiServer()
}

// UnimplementedDataRetentionApiServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDataRetentionApiServer struct{}

func (UnimplementedDataRetentionApiServer) GetDataRetention(context.Context, *GetDataRetentionRequest) (*DataRetention, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDataRetention not implemented")
}
func (UnimplementedDataRetentionApiServer) PullDataRetention(*PullDataRetentionRequest, grpc.ServerStreamingServer[PullDataRetentionResponse]) error {
	return status.Errorf(codes.Unimplemented, "method PullDataRetention not implemented")
}
func (UnimplementedDataRetentionApiServer) PurgeDataRetention(context.Context, *PurgeDataRetentionRequest) (*PurgeDataRetentionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PurgeDataRetention not implemented")
}
func (UnimplementedDataRetentionApiServer) CompactDataRetention(context.Context, *CompactDataRetentionRequest) (*CompactDataRetentionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CompactDataRetention not implemented")
}
func (UnimplementedDataRetentionApiServer) mustEmbedUnimplementedDataRetentionApiServer() {}
func (UnimplementedDataRetentionApiServer) testEmbeddedByValue()                          {}

// UnsafeDataRetentionApiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DataRetentionApiServer will
// result in compilation errors.
type UnsafeDataRetentionApiServer interface {
	mustEmbedUnimplementedDataRetentionApiServer()
}

func RegisterDataRetentionApiServer(s grpc.ServiceRegistrar, srv DataRetentionApiServer) {
	// If the following call pancis, it indicates UnimplementedDataRetentionApiServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DataRetentionApi_ServiceDesc, srv)
}

func _DataRetentionApi_GetDataRetention_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDataRetentionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataRetentionApiServer).GetDataRetention(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataRetentionApi_GetDataRetention_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataRetentionApiServer).GetDataRetention(ctx, req.(*GetDataRetentionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataRetentionApi_PullDataRetention_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PullDataRetentionRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DataRetentionApiServer).PullDataRetention(m, &grpc.GenericServerStream[PullDataRetentionRequest, PullDataRetentionResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataRetentionApi_PullDataRetentionServer = grpc.ServerStreamingServer[PullDataRetentionResponse]

func _DataRetentionApi_PurgeDataRetention_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PurgeDataRetentionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataRetentionApiServer).PurgeDataRetention(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataRetentionApi_PurgeDataRetention_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataRetentionApiServer).PurgeDataRetention(ctx, req.(*PurgeDataRetentionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataRetentionApi_CompactDataRetention_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompactDataRetentionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataRetentionApiServer).CompactDataRetention(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataRetentionApi_CompactDataRetention_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataRetentionApiServer).CompactDataRetention(ctx, req.(*CompactDataRetentionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DataRetentionApi_ServiceDesc is the grpc.ServiceDesc for DataRetentionApi service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DataRetentionApi_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "smartcore.bos.dataretention.v1.DataRetentionApi",
	HandlerType: (*DataRetentionApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDataRetention",
			Handler:    _DataRetentionApi_GetDataRetention_Handler,
		},
		{
			MethodName: "PurgeDataRetention",
			Handler:    _DataRetentionApi_PurgeDataRetention_Handler,
		},
		{
			MethodName: "CompactDataRetention",
			Handler:    _DataRetentionApi_CompactDataRetention_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PullDataRetention",
			Handler:       _DataRetentionApi_PullDataRetention_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "smartcore/bos/dataretention/v1/data_retention.proto",
}

const (
	DataRetentionInfo_DescribeDataRetention_FullMethodName = "/smartcore.bos.dataretention.v1.DataRetentionInfo/DescribeDataRetention"
)

// DataRetentionInfoClient is the client API for DataRetentionInfo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DataRetentionInfo provides metadata about what a device supports for the data retention trait.
type DataRetentionInfoClient interface {
	DescribeDataRetention(ctx context.Context, in *DescribeDataRetentionRequest, opts ...grpc.CallOption) (*DataRetentionSupport, error)
}

type dataRetentionInfoClient struct {
	cc grpc.ClientConnInterface
}

func NewDataRetentionInfoClient(cc grpc.ClientConnInterface) DataRetentionInfoClient {
	return &dataRetentionInfoClient{cc}
}

func (c *dataRetentionInfoClient) DescribeDataRetention(ctx context.Context, in *DescribeDataRetentionRequest, opts ...grpc.CallOption) (*DataRetentionSupport, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DataRetentionSupport)
	err := c.cc.Invoke(ctx, DataRetentionInfo_DescribeDataRetention_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataRetentionInfoServer is the server API for DataRetentionInfo service.
// All implementations must embed UnimplementedDataRetentionInfoServer
// for forward compatibility.
//
// DataRetentionInfo provides metadata about what a device supports for the data retention trait.
type DataRetentionInfoServer interface {
	DescribeDataRetention(context.Context, *DescribeDataRetentionRequest) (*DataRetentionSupport, error)
	mustEmbedUnimplementedDataRetentionInfoServer()
}

// UnimplementedDataRetentionInfoServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDataRetentionInfoServer struct{}

func (UnimplementedDataRetentionInfoServer) DescribeDataRetention(context.Context, *DescribeDataRetentionRequest) (*DataRetentionSupport, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DescribeDataRetention not implemented")
}
func (UnimplementedDataRetentionInfoServer) mustEmbedUnimplementedDataRetentionInfoServer() {}
func (UnimplementedDataRetentionInfoServer) testEmbeddedByValue()                           {}

// UnsafeDataRetentionInfoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DataRetentionInfoServer will
// result in compilation errors.
type UnsafeDataRetentionInfoServer interface {
	mustEmbedUnimplementedDataRetentionInfoServer()
}

func RegisterDataRetentionInfoServer(s grpc.ServiceRegistrar, srv DataRetentionInfoServer) {
	// If the following call pancis, it indicates UnimplementedDataRetentionInfoServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DataRetentionInfo_ServiceDesc, srv)
}

func _DataRetentionInfo_DescribeDataRetention_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescribeDataRetentionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataRetentionInfoServer).DescribeDataRetention(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataRetentionInfo_DescribeDataRetention_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataRetentionInfoServer).DescribeDataRetention(ctx, req.(*DescribeDataRetentionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DataRetentionInfo_ServiceDesc is the grpc.ServiceDesc for DataRetentionInfo service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DataRetentionInfo_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "smartcore.bos.dataretention.v1.DataRetentionInfo",
	HandlerType: (*DataRetentionInfoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DescribeDataRetention",
			Handler:    _DataRetentionInfo_DescribeDataRetention_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "smartcore/bos/dataretention/v1/data_retention.proto",
}
