// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: smartcore/bos/microphone/v1/microphone.proto

package microphonepb

import (
	typespb "github.com/smart-core-os/sc-bos/pkg/proto/typespb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GainSupport describes the capabilities of devices implementing this trait.
type GainSupport struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// How a named device supports read/write/pull apis
	ResourceSupport *typespb.ResourceSupport `protobuf:"bytes,1,opt,name=resource_support,json=resourceSupport,proto3" json:"resource_support,omitempty"`
	// Attributes associated with the gain property of the microphone. Note that a step value that is the same as the bounds
	// implies that the microphone only supports mute
	GainAttributes *typespb.FloatAttributes `protobuf:"bytes,2,opt,name=gain_attributes,json=gainAttributes,proto3" json:"gain_attributes,omitempty"`
	// How is mute implemented by the device. Can help to customise behaviour of interfaces to the device, e.g. by
	// disallowing gain change when muted
	MuteSupport   typespb.MuteSupport `protobuf:"varint,3,opt,name=mute_support,json=muteSupport,proto3,enum=smartcore.bos.types.v1.MuteSupport" json:"mute_support,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GainSupport) Reset() {
	*x = GainSupport{}
	mi := &file_smartcore_bos_microphone_v1_microphone_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GainSupport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GainSupport) ProtoMessage() {}

func (x *GainSupport) ProtoReflect() protoreflect.Message {
	mi := &file_smartcore_bos_microphone_v1_microphone_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GainSupport.ProtoReflect.Descriptor instead.
func (*GainSupport) Descriptor() ([]byte, []int) {
	return file_smartcore_bos_microphone_v1_microphone_proto_rawDescGZIP(), []int{0}
}

func (x *GainSupport) GetResourceSupport() *typespb.ResourceSupport {
	if x != nil {
		return x.ResourceSupport
	}
	return nil
}

func (x *GainSupport) GetGainAttributes() *typespb.FloatAttributes {
	if x != nil {
		return x.GainAttributes
	}
	return nil
}

func (x *GainSupport) GetMuteSupport() typespb.MuteSupport {
	if x != nil {
		return x.MuteSupport
	}
	return typespb.MuteSupport(0)
}

type GetMicrophoneGainRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the device to fetch the state for
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// fields to fetch relative the the AudioLevel type
	ReadMask      *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=read_mask,json=readMask,proto3" json:"read_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMicrophoneGainRequest) Reset() {
	*x = GetMicrophoneGainRequest{}
	mi := &file_smartcore_bos_microphone_v1_microphone_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMicrophoneGainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMicrophoneGainRequest) ProtoMessage() {}

func (x *GetMicrophoneGainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_smartcore_bos_microphone_v1_microphone_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMicrophoneGainRequest.ProtoReflect.Descriptor instead.
func (*GetMicrophoneGainRequest) Descriptor() ([]byte, []int) {
	return file_smartcore_bos_microphone_v1_microphone_proto_rawDescGZIP(), []int{1}
}

func (x *GetMicrophoneGainRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetMicrophoneGainRequest) GetReadMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.ReadMask
	}
	return nil
}

type UpdateMicrophoneGainRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the device to update the state for
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The updated gain value
	Gain *typespb.AudioLevel `protobuf:"bytes,2,opt,name=gain,proto3" json:"gain,omitempty"`
	// Only supported for AudioLevel.gain. Update the value relative to the current value.
	Delta bool `protobuf:"varint,3,opt,name=delta,proto3" json:"delta,omitempty"`
	// The fields we intend to update relative to the AudioLevel type
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,4,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMicrophoneGainRequest) Reset() {
	*x = UpdateMicrophoneGainRequest{}
	mi := &file_smartcore_bos_microphone_v1_microphone_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMicrophoneGainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMicrophoneGainRequest) ProtoMessage() {}

func (x *UpdateMicrophoneGainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_smartcore_bos_microphone_v1_microphone_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMicrophoneGainRequest.ProtoReflect.Descriptor instead.
func (*UpdateMicrophoneGainRequest) Descriptor() ([]byte, []int) {
	return file_smartcore_bos_microphone_v1_microphone_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateMicrophoneGainRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateMicrophoneGainRequest) GetGain() *typespb.AudioLevel {
	if x != nil {
		return x.Gain
	}
	return nil
}

func (x *UpdateMicrophoneGainRequest) GetDelta() bool {
	if x != nil {
		return x.Delta
	}
	return false
}

func (x *UpdateMicrophoneGainRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

type PullMicrophoneGainRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the device to fetch the state for
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// fields to fetch relative the the AudioLevel type
	ReadMask *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=read_mask,json=readMask,proto3" json:"read_mask,omitempty"`
	// When true the device will only send changes to the resource value.
	// The default behaviour is to send the current value immediately followed by any updates as they happen.
	UpdatesOnly   bool `protobuf:"varint,3,opt,name=updates_only,json=updatesOnly,proto3" json:"updates_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullMicrophoneGainRequest) Reset() {
	*x = PullMicrophoneGainRequest{}
	mi := &file_smartcore_bos_microphone_v1_microphone_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullMicrophoneGainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullMicrophoneGainRequest) ProtoMessage() {}

func (x *PullMicrophoneGainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_smartcore_bos_microphone_v1_microphone_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullMicrophoneGainRequest.ProtoReflect.Descriptor instead.
func (*PullMicrophoneGainRequest) Descriptor() ([]byte, []int) {
	return file_smartcore_bos_microphone_v1_microphone_proto_rawDescGZIP(), []int{3}
}

func (x *PullMicrophoneGainRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PullMicrophoneGainRequest) GetReadMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.ReadMask
	}
	return nil
}

func (x *PullMicrophoneGainRequest) GetUpdatesOnly() bool {
	if x != nil {
		return x.UpdatesOnly
	}
	return false
}

type PullMicrophoneGainResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Changes since the last message
	Changes       []*typespb.AudioLevelChange `protobuf:"bytes,1,rep,name=changes,proto3" json:"changes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullMicrophoneGainResponse) Reset() {
	*x = PullMicrophoneGainResponse{}
	mi := &file_smartcore_bos_microphone_v1_microphone_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullMicrophoneGainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullMicrophoneGainResponse) ProtoMessage() {}

func (x *PullMicrophoneGainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_smartcore_bos_microphone_v1_microphone_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullMicrophoneGainResponse.ProtoReflect.Descriptor instead.
func (*PullMicrophoneGainResponse) Descriptor() ([]byte, []int) {
	return file_smartcore_bos_microphone_v1_microphone_proto_rawDescGZIP(), []int{4}
}

func (x *PullMicrophoneGainResponse) GetChanges() []*typespb.AudioLevelChange {
	if x != nil {
		return x.Changes
	}
	return nil
}

type DescribeGainRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the device
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeGainRequest) Reset() {
	*x = DescribeGainRequest{}
	mi := &file_smartcore_bos_microphone_v1_microphone_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeGainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeGainRequest) ProtoMessage() {}

func (x *DescribeGainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_smartcore_bos_microphone_v1_microphone_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeGainRequest.ProtoReflect.Descriptor instead.
func (*DescribeGainRequest) Descriptor() ([]byte, []int) {
	return file_smartcore_bos_microphone_v1_microphone_proto_rawDescGZIP(), []int{5}
}

func (x *DescribeGainRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_smartcore_bos_microphone_v1_microphone_proto protoreflect.FileDescriptor

const file_smartcore_bos_microphone_v1_microphone_proto_rawDesc = "" +
	"\n" +
	",smartcore/bos/microphone/v1/microphone.proto\x12\x1bsmartcore.bos.microphone.v1\x1a google/protobuf/field_mask.proto\x1a!smartcore/bos/types/v1/info.proto\x1a#smartcore/bos/types/v1/number.proto\x1a!smartcore/bos/types/v1/unit.proto\"\xfb\x01\n" +
	"\vGainSupport\x12R\n" +
	"\x10resource_support\x18\x01 \x01(\v2'.smartcore.bos.types.v1.ResourceSupportR\x0fresourceSupport\x12P\n" +
	"\x0fgain_attributes\x18\x02 \x01(\v2'.smartcore.bos.types.v1.FloatAttributesR\x0egainAttributes\x12F\n" +
	"\fmute_support\x18\x03 \x01(\x0e2#.smartcore.bos.types.v1.MuteSupportR\vmuteSupport\"g\n" +
	"\x18GetMicrophoneGainRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x127\n" +
	"\tread_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\breadMask\"\xbc\x01\n" +
	"\x1bUpdateMicrophoneGainRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x126\n" +
	"\x04gain\x18\x02 \x01(\v2\".smartcore.bos.types.v1.AudioLevelR\x04gain\x12\x14\n" +
	"\x05delta\x18\x03 \x01(\bR\x05delta\x12;\n" +
	"\vupdate_mask\x18\x04 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\"\x8b\x01\n" +
	"\x19PullMicrophoneGainRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x127\n" +
	"\tread_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\breadMask\x12!\n" +
	"\fupdates_only\x18\x03 \x01(\bR\vupdatesOnly\"`\n" +
	"\x1aPullMicrophoneGainResponse\x12B\n" +
	"\achanges\x18\x01 \x03(\v2(.smartcore.bos.types.v1.AudioLevelChangeR\achanges\")\n" +
	"\x13DescribeGainRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name2\xe0\x02\n" +
	"\rMicrophoneApi\x12d\n" +
	"\aGetGain\x125.smartcore.bos.microphone.v1.GetMicrophoneGainRequest\x1a\".smartcore.bos.types.v1.AudioLevel\x12j\n" +
	"\n" +
	"UpdateGain\x128.smartcore.bos.microphone.v1.UpdateMicrophoneGainRequest\x1a\".smartcore.bos.types.v1.AudioLevel\x12}\n" +
	"\bPullGain\x126.smartcore.bos.microphone.v1.PullMicrophoneGainRequest\x1a7.smartcore.bos.microphone.v1.PullMicrophoneGainResponse0\x012|\n" +
	"\x0eMicrophoneInfo\x12j\n" +
	"\fDescribeGain\x120.smartcore.bos.microphone.v1.DescribeGainRequest\x1a(.smartcore.bos.microphone.v1.GainSupportB8Z6github.com/smart-core-os/sc-bos/pkg/proto/microphonepbb\x06proto3"

var (
	file_smartcore_bos_microphone_v1_microphone_proto_rawDescOnce sync.Once
	file_smartcore_bos_microphone_v1_microphone_proto_rawDescData []byte
)

func file_smartcore_bos_microphone_v1_microphone_proto_rawDescGZIP() []byte {
	file_smartcore_bos_microphone_v1_microphone_proto_rawDescOnce.Do(func() {
		file_smartcore_bos_microphone_v1_microphone_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_smartcore_bos_microphone_v1_microphone_proto_rawDesc), len(file_smartcore_bos_microphone_v1_microphone_proto_rawDesc)))
	})
	return file_smartcore_bos_microphone_v1_microphone_proto_rawDescData
}

var file_smartcore_bos_microphone_v1_microphone_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_smartcore_bos_microphone_v1_microphone_proto_goTypes = []any{
	(*GainSupport)(nil),                 // 0: smartcore.bos.microphone.v1.GainSupport
	(*GetMicrophoneGainRequest)(nil),    // 1: smartcore.bos.microphone.v1.GetMicrophoneGainRequest
	(*UpdateMicrophoneGainRequest)(nil), // 2: smartcore.bos.microphone.v1.UpdateMicrophoneGainRequest
	(*PullMicrophoneGainRequest)(nil),   // 3: smartcore.bos.microphone.v1.PullMicrophoneGainRequest
	(*PullMicrophoneGainResponse)(nil),  // 4: smartcore.bos.microphone.v1.PullMicrophoneGainResponse
	(*DescribeGainRequest)(nil),         // 5: smartcore.bos.microphone.v1.DescribeGainRequest
	(*typespb.ResourceSupport)(nil),     // 6: smartcore.bos.types.v1.ResourceSupport
	(*typespb.FloatAttributes)(nil),     // 7: smartcore.bos.types.v1.FloatAttributes
	(typespb.MuteSupport)(0),            // 8: smartcore.bos.types.v1.MuteSupport
	(*fieldmaskpb.FieldMask)(nil),       // 9: google.protobuf.FieldMask
	(*typespb.AudioLevel)(nil),          // 10: smartcore.bos.types.v1.AudioLevel
	(*typespb.AudioLevelChange)(nil),    // 11: smartcore.bos.types.v1.AudioLevelChange
}
var file_smartcore_bos_microphone_v1_microphone_proto_depIdxs = []int32{
	6,  // 0: smartcore.bos.microphone.v1.GainSupport.resource_support:type_name -> smartcore.bos.types.v1.ResourceSupport
	7,  // 1: smartcore.bos.microphone.v1.GainSupport.gain_attributes:type_name -> smartcore.bos.types.v1.FloatAttributes
	8,  // 2: smartcore.bos.microphone.v1.GainSupport.mute_support:type_name -> smartcore.bos.types.v1.MuteSupport
	9,  // 3: smartcore.bos.microphone.v1.GetMicrophoneGainRequest.read_mask:type_name -> google.protobuf.FieldMask
	10, // 4: smartcore.bos.microphone.v1.UpdateMicrophoneGainRequest.gain:type_name -> smartcore.bos.types.v1.AudioLevel
	9,  // 5: smartcore.bos.microphone.v1.UpdateMicrophoneGainRequest.update_mask:type_name -> google.protobuf.FieldMask
	9,  // 6: smartcore.bos.microphone.v1.PullMicrophoneGainRequest.read_mask:type_name -> google.protobuf.FieldMask
	11, // 7: smartcore.bos.microphone.v1.PullMicrophoneGainResponse.changes:type_name -> smartcore.bos.types.v1.AudioLevelChange
	1,  // 8: smartcore.bos.microphone.v1.MicrophoneApi.GetGain:input_type -> smartcore.bos.microphone.v1.GetMicrophoneGainRequest
	2,  // 9: smartcore.bos.microphone.v1.MicrophoneApi.UpdateGain:input_type -> smartcore.bos.microphone.v1.UpdateMicrophoneGainRequest
	3,  // 10: smartcore.bos.microphone.v1.MicrophoneApi.PullGain:input_type -> smartcore.bos.microphone.v1.PullMicrophoneGainRequest
	5,  // 11: smartcore.bos.microphone.v1.MicrophoneInfo.DescribeGain:input_type -> smartcore.bos.microphone.v1.DescribeGainRequest
	10, // 12: smartcore.bos.microphone.v1.MicrophoneApi.GetGain:output_type -> smartcore.bos.types.v1.AudioLevel
	10, // 13: smartcore.bos.microphone.v1.MicrophoneApi.UpdateGain:output_type -> smartcore.bos.types.v1.AudioLevel
	4,  // 14: smartcore.bos.microphone.v1.MicrophoneApi.PullGain:output_type -> smartcore.bos.microphone.v1.PullMicrophoneGainResponse
	0,  // 15: smartcore.bos.microphone.v1.MicrophoneInfo.DescribeGain:output_type -> smartcore.bos.microphone.v1.GainSupport
	12, // [12:16] is the sub-list for method output_type
	8,  // [8:12] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_smartcore_bos_microphone_v1_microphone_proto_init() }
func file_smartcore_bos_microphone_v1_microphone_proto_init() {
	if File_smartcore_bos_microphone_v1_microphone_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_smartcore_bos_microphone_v1_microphone_proto_rawDesc), len(file_smartcore_bos_microphone_v1_microphone_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_smartcore_bos_microphone_v1_microphone_proto_goTypes,
		DependencyIndexes: file_smartcore_bos_microphone_v1_microphone_proto_depIdxs,
		MessageInfos:      file_smartcore_bos_microphone_v1_microphone_proto_msgTypes,
	}.Build()
	File_smartcore_bos_microphone_v1_microphone_proto = out.File
	file_smartcore_bos_microphone_v1_microphone_proto_goTypes = nil
	file_smartcore_bos_microphone_v1_microphone_proto_depIdxs = nil
}
