// Code generated by protoc-gen-wrapper. DO NOT EDIT.

package microphonepb

import (
	wrap "github.com/smart-core-os/sc-bos/pkg/wrap"
	grpc "google.golang.org/grpc"
)

// WrapInfo	adapts a MicrophoneInfoServer	and presents it as a MicrophoneInfoClient
func WrapInfo(server MicrophoneInfoServer) *InfoWrapper {
	conn := wrap.ServerToClient(MicrophoneInfo_ServiceDesc, server)
	client := NewMicrophoneInfoClient(conn)
	return &InfoWrapper{
		MicrophoneInfoClient: client,
		server:               server,
		conn:                 conn,
		desc:                 MicrophoneInfo_ServiceDesc,
	}
}

type InfoWrapper struct {
	MicrophoneInfoClient

	server MicrophoneInfoServer
	conn   grpc.ClientConnInterface
	desc   grpc.ServiceDesc
}

// UnwrapServer returns the underlying server instance.
func (w *InfoWrapper) UnwrapServer() MicrophoneInfoServer {
	return w.server
}

// Unwrap implements wrap.Unwrapper and returns the underlying server instance as an unknown type.
func (w *InfoWrapper) Unwrap() any {
	return w.UnwrapServer()
}

func (w *InfoWrapper) UnwrapService() (grpc.ClientConnInterface, grpc.ServiceDesc) {
	return w.conn, w.desc
}
