package main

import (
	"github.com/google/uuid"
	"sigs.k8s.io/yaml"

	"github.com/smart-core-os/sc-bos/pkg/dbo"
	"github.com/smart-core-os/sc-bos/pkg/proto/meterpb"
)

// header is prepended to generated output. It documents the placeholders that a
// human/operator must resolve before the building-config is authoritative.
const header = `# Generated by cmd/tools/gen-dbo — Google Digital Buildings building configuration.
#
# PLACEHOLDERS TO RESOLVE before use:
#   * type: an energy-only meter has NO canonical DBO type (every METERS/EM_PWM*
#     requires power_sensor). The emitted type is a non-canonical placeholder —
#     replace with a passthrough/proposed type, or add power reporting.
#   * cloud_device_id: BOS has no Google device-registry id; the Smart Core device
#     name is used as a placeholder. Replace with the real numeric registry id.
#
# Point names are DBO standard fields, so each translation present_value path is an
# identity mapping. units.values maps the DBO unit name to the raw device string.
`

// BuildingConfig is a Google Digital Buildings building-configuration file: entities
// keyed by GUID. Marshalled to YAML via JSON tags (sigs.k8s.io/yaml).
type BuildingConfig map[string]Entity

// Entity is one reporting device in the building config.
type Entity struct {
	Code          string                      `json:"code"`
	Type          string                      `json:"type"`
	CloudDeviceID string                      `json:"cloud_device_id,omitempty"`
	Translation   map[string]FieldTranslation `json:"translation,omitempty"`
}

// FieldTranslation maps a DBO standard field to the device's raw payload paths.
type FieldTranslation struct {
	PresentValue string `json:"present_value"`
	Units        *Units `json:"units,omitempty"`
}

// Units binds the DBO unit name to the raw unit string the device reports at the
// UDMI units path.
type Units struct {
	Key    string            `json:"key"`
	Values map[string]string `json:"values"`
}

// deviceGUID derives a stable UUIDv5 for a device from its Smart Core name, so
// re-running the generator yields the same entity keys.
func deviceGUID(name string) string {
	return uuid.NewSHA1(uuid.NameSpaceURL, []byte("smartcore-bos:"+name)).String()
}

// meterEntity builds the DBO building-config entity for a meter device from its
// name and reading support. Point names are DBO standard fields (so present_value
// is an identity path); units.values maps the DBO unit name → the raw device unit.
// The entity type and cloud_device_id are placeholders (see header).
func meterEntity(name string, support *meterpb.MeterReadingSupport) (guid string, e Entity) {
	typeName, _ := dbo.MeterEntityType()
	e = Entity{
		Code:          name,
		Type:          typeName,
		CloudDeviceID: name, // placeholder — no GCP registry id available
		Translation:   map[string]FieldTranslation{},
	}
	for _, f := range dbo.MeterFields(support.GetUsageUnit(), support.GetProducedUnit()) {
		ft := FieldTranslation{
			PresentValue: "points." + f.Field + ".present_value",
		}
		if f.Unit != "" {
			// The units key uses ".units" (plural), matching UDMI, DBO's
			// building-config examples, and DBO's own code comment. NB DBO's
			// instance_validator _UDMI_UNIT_FIELD_REGEX is ".unit" (singular) and
			// won't match plural — a bug in the validator, not here; plural is the
			// documented/wire-correct form.
			ft.Units = &Units{
				Key:    "pointset.points." + f.Field + ".units",
				Values: map[string]string{f.Unit: f.RawUnit},
			}
		}
		e.Translation[f.Field] = ft
	}
	return deviceGUID(name), e
}

// Marshal renders the building config to YAML with the placeholder header. Map keys
// (entity GUIDs, translation fields, unit values) serialise in a deterministic
// order, so output is stable across runs.
func (bc BuildingConfig) Marshal() ([]byte, error) {
	body, err := yaml.Marshal(bc)
	if err != nil {
		return nil, err
	}
	return append([]byte(header), body...), nil
}
