// Code generated by protoc-gen-wrapper. DO NOT EDIT.

package brightnesssensorpb

import (
	"google.golang.org/grpc"

	"github.com/smart-core-os/sc-api/go/traits"
	"github.com/smart-core-os/sc-bos/pkg/wrap"
)

// WrapApi	adapts a traits.BrightnessSensorApiServer	and presents it as a traits.BrightnessSensorApiClient
func WrapApi(server traits.BrightnessSensorApiServer) *ApiWrapper {
	conn := wrap.ServerToClient(traits.BrightnessSensorApi_ServiceDesc, server)
	client := traits.NewBrightnessSensorApiClient(conn)
	return &ApiWrapper{
		BrightnessSensorApiClient: client,
		server:                    server,
		conn:                      conn,
		desc:                      traits.BrightnessSensorApi_ServiceDesc,
	}
}

type ApiWrapper struct {
	traits.BrightnessSensorApiClient

	server traits.BrightnessSensorApiServer
	conn   grpc.ClientConnInterface
	desc   grpc.ServiceDesc
}

// UnwrapServer returns the underlying server instance.
func (w *ApiWrapper) UnwrapServer() traits.BrightnessSensorApiServer {
	return w.server
}

// Unwrap implements wrap.Unwrapper and returns the underlying server instance as an unknown type.
func (w *ApiWrapper) Unwrap() any {
	return w.UnwrapServer()
}

func (w *ApiWrapper) UnwrapService() (grpc.ClientConnInterface, grpc.ServiceDesc) {
	return w.conn, w.desc
}
