export const widgetDescriptions = {
  'building/BuildingFloors': 'This widget shows a list of all floors in the building. It helps you understand the building layout and quickly jump to a specific floor to see more details.',
  'building/FloorTraitCells': 'This shows a detailed health check for each floor. It uses color-coded chips for things like Temperature, CO2, and Noise. Green means everything is great, while orange and red suggest things that might need adjustment. It also shows arrows if conditions are getting better or worse compared to yesterday.',
  'container/FlexRow': 'A simple container that neatly arranges multiple small widgets in a single row.',
  'energy/DemandHistoryCard': 'Shows your building\'s "thirst" for power over time. It helps you see when you are using the most electricity, which is often when costs are highest.',
  'energy/IdleEnergyCard': 'Shows how much energy is being used when the building is supposed to be "asleep" (like at night or on weekends). Reducing this "vampire power" is one of the easiest ways to save money.',
  'energy/PowerCompareCard': 'A side-by-side comparison of power usage across different areas or equipment, making it easy to spot the biggest energy users.',
  'energy/PowerCompareChart': 'A chart that plots power usage for multiple areas over time, helping you see how different parts of your building interact and compete for energy.',
  'energy/PowerFactorCard': 'Measures how efficiently your building uses the electricity it draws. A low score means energy is being wasted in the wires, which might lead to extra charges from the utility company.',
  'environmental/AirQualityCard': 'Gives a quick "Air Health" score for a room. It looks at factors like CO2 and chemicals in the air to tell you if the ventilation is doing its job.',
  'environmental/ComfortScoreCard': 'Combines temperature, humidity, and air quality into a single "Happiness Score" for the space. It tells you at a glance if the environment is comfortable for people.',
  'environmental/AirQualityHistoryCard': 'Shows how the air quality has changed over the last few hours or days. This helps you find patterns, like if air gets "stuffy" every afternoon when more people arrive.',
  'environmental/AirQualityHistoryChart': 'A detailed graph of air quality trends. It tracks things like CO2 (stale air) and dust levels over time so you can see exactly when conditions change.',
  'environmental/AirTemperatureHistoryCard': 'Tracks how the temperature has shifted over time. It helps you see if the heating or cooling is keeping the space steady or if it\'s swinging too much.',
  'environmental/AirTemperatureHistoryChart': 'A visual graph of temperature over time, making it easy to see if the building stays comfortable through the day and night.',
  'environmental/EnvironmentalCard': 'A "weather station" for your indoor space. It shows real-time readings for temperature, humidity, noise, and air cleanliness all in one place.',
  'environmental/SoundSensorHistoryChart': 'Shows how noisy a space has been. This is great for identifying loud periods in a workspace or checking if equipment is making too much noise at night.',
  'environmental/SoundSensorHistoryCard': 'A summary of recent noise levels, helping you understand the "volume" of a room over time.',
  'meter/EnergyVsBaselineCard': 'Shows if you are using more or less energy than usual. It compares today\'s usage against a "normal" day (like the same day last week). A green badge means you are saving energy, while red means you are using more.',
  'meter/MeterDensityCard': 'Shows which areas are the "densest" energy users for their size. It helps identify rooms that use a lot of power even if they are small.',
  'meter/MeterHistoryCard': 'A deep-dive into the history of a specific energy meter, showing every drop of energy used over weeks or months.',
  'notifications/ZoneNotifications': 'A digital "to-do list" or alert log for a specific area. It shows recent problems or important messages that need your attention.',
  'occupancy/OccupancyCard': 'Shows if people are currently using a space and, if the sensors allow, roughly how many people are there right now.',
  'occupancy/PeopleCountCard': 'A real-time "headcount" of how many people are in a room or building at this very moment.',
  'occupancy/PeopleCountHistoryChart': 'A graph showing how the number of people in a space changes through the day. This is perfect for seeing when your building is most crowded.',
  'occupancy/PeopleCountHistoryCard': 'A summary of people traffic over time, helping you understand how different spaces are being used.',
  'occupancy/PresenceCard': 'A simple "Occupied" or "Vacant" sign that updates automatically based on motion sensors in the room.',
  'power-history/PowerHistoryCard': 'A historical look at your total power usage. It helps you see long-term trends and whether your energy-saving efforts are working over time.',
  'security/SecurityEventsCard': 'Lists recent security activities, like doors being opened or motion detected after hours, so you can keep the building safe.',
  'usage/AllocationHistoryCard': 'Shows how many items like desks, lockers, or rooms are currently being used and who has them. This helps you understand which resources are popular and how they are being shared.',
  'devices/DeviceTable': 'A comprehensive list of every piece of equipment in an area, showing its current status and whether it\'s working correctly.',
  'environmental/AirTemperatureChip': 'A tiny, quick-glance indicator of the current temperature in a specific spot.',
  'health/HealthImpactBreakdownsCard': 'Explains *why* a space might be feeling unhealthy, breaking down the impact of things like poor air or uncomfortable temperatures on occupants.',
  'health/HealthCheckTable': 'A maintenance checklist that shows the status of various systems, highlighting anything that needs a technician\'s eyes.',
  'meter/ConsumptionCard': 'Shows the total amount of energy or resources used by a specific meter over a selected period of time.',
  'power-total/PowerTotal': 'Shows the total amount of electricity being used by the entire facility or a major system right now.',
};
