// Code generated by protoc-gen-router. DO NOT EDIT.

package occupancysensorpb

import (
	context "context"
	fmt "fmt"
	router "github.com/smart-core-os/sc-bos/pkg/router"
	grpc "google.golang.org/grpc"
	io "io"
)

// ApiRouter is a OccupancySensorApiServer that allows routing named requests to specific OccupancySensorApiClient
// Deprecated: routing is now handled dynamically by [node.Node].
type ApiRouter struct {
	UnimplementedOccupancySensorApiServer

	router.Router
}

// compile time check that we implement the interface we need
var _ OccupancySensorApiServer = (*ApiRouter)(nil)

// NewApiRouter constructs a new empty ApiRouter with the provided options.
// Deprecated: routing is now handled dynamically by [node.Node].
func NewApiRouter(opts ...router.Option) *ApiRouter {
	return &ApiRouter{
		Router: router.NewRouter(opts...),
	}
}

// WithOccupancySensorApiClientFactory instructs the router to create a new
// client the first time Get is called for that name.
func WithOccupancySensorApiClientFactory(f func(name string) (OccupancySensorApiClient, error)) router.Option {
	return router.WithFactory(func(name string) (any, error) {
		return f(name)
	})
}

func (r *ApiRouter) Register(server grpc.ServiceRegistrar) {
	RegisterOccupancySensorApiServer(server, r)
}

// Add extends Router.Add to panic if client is not of type OccupancySensorApiClient.
func (r *ApiRouter) Add(name string, client any) any {
	if !r.HoldsType(client) {
		panic(fmt.Sprintf("not correct type: client of type %T is not a OccupancySensorApiClient", client))
	}
	return r.Router.Add(name, client)
}

func (r *ApiRouter) HoldsType(client any) bool {
	_, ok := client.(OccupancySensorApiClient)
	return ok
}

func (r *ApiRouter) AddOccupancySensorApiClient(name string, client OccupancySensorApiClient) OccupancySensorApiClient {
	res := r.Add(name, client)
	if res == nil {
		return nil
	}
	return res.(OccupancySensorApiClient)
}

func (r *ApiRouter) RemoveOccupancySensorApiClient(name string) OccupancySensorApiClient {
	res := r.Remove(name)
	if res == nil {
		return nil
	}
	return res.(OccupancySensorApiClient)
}

func (r *ApiRouter) GetOccupancySensorApiClient(name string) (OccupancySensorApiClient, error) {
	res, err := r.Get(name)
	if err != nil {
		return nil, err
	}
	if res == nil {
		return nil, nil
	}
	return res.(OccupancySensorApiClient), nil
}

func (r *ApiRouter) GetOccupancy(ctx context.Context, request *GetOccupancyRequest) (*Occupancy, error) {
	child, err := r.GetOccupancySensorApiClient(request.Name)
	if err != nil {
		return nil, err
	}

	return child.GetOccupancy(ctx, request)
}

func (r *ApiRouter) PullOccupancy(request *PullOccupancyRequest, server OccupancySensorApi_PullOccupancyServer) error {
	child, err := r.GetOccupancySensorApiClient(request.Name)
	if err != nil {
		return err
	}

	// so we can cancel our forwarding request if we can't send responses to our caller
	reqCtx, reqDone := context.WithCancel(server.Context())
	// issue the request
	stream, err := child.PullOccupancy(reqCtx, request)
	if err != nil {
		return err
	}

	// send the stream header
	header, err := stream.Header()
	if err != nil {
		return err
	}
	if err = server.SendHeader(header); err != nil {
		return err
	}

	// send all the messages
	// false means the error is from the child, true means the error is from the caller
	var callerError bool
	for {
		// Impl note: we could improve throughput here by issuing the Recv and Send in different goroutines, but we're doing
		// it synchronously until we have a need to change the behaviour

		var msg *PullOccupancyResponse
		msg, err = stream.Recv()
		if err != nil {
			break
		}

		err = server.Send(msg)
		if err != nil {
			callerError = true
			break
		}
	}

	// err is guaranteed to be non-nil as it's the only way to exit the loop
	if callerError {
		// cancel the request
		reqDone()
		return err
	} else {
		if trailer := stream.Trailer(); trailer != nil {
			server.SetTrailer(trailer)
		}
		if err == io.EOF {
			return nil
		}
		return err
	}
}
