// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.32.1
// source: traits/open_close.proto

package traits

import (
	types "github.com/smart-core-os/sc-api/go/types"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Possible directions the device can open/close
type OpenClosePosition_Direction int32

const (
	OpenClosePosition_DIRECTION_UNSPECIFIED OpenClosePosition_Direction = 0
	OpenClosePosition_UP                    OpenClosePosition_Direction = 1
	OpenClosePosition_DOWN                  OpenClosePosition_Direction = 2
	OpenClosePosition_LEFT                  OpenClosePosition_Direction = 3
	OpenClosePosition_RIGHT                 OpenClosePosition_Direction = 4
	OpenClosePosition_IN                    OpenClosePosition_Direction = 5
	OpenClosePosition_OUT                   OpenClosePosition_Direction = 6
)

// Enum value maps for OpenClosePosition_Direction.
var (
	OpenClosePosition_Direction_name = map[int32]string{
		0: "DIRECTION_UNSPECIFIED",
		1: "UP",
		2: "DOWN",
		3: "LEFT",
		4: "RIGHT",
		5: "IN",
		6: "OUT",
	}
	OpenClosePosition_Direction_value = map[string]int32{
		"DIRECTION_UNSPECIFIED": 0,
		"UP":                    1,
		"DOWN":                  2,
		"LEFT":                  3,
		"RIGHT":                 4,
		"IN":                    5,
		"OUT":                   6,
	}
)

func (x OpenClosePosition_Direction) Enum() *OpenClosePosition_Direction {
	p := new(OpenClosePosition_Direction)
	*p = x
	return p
}

func (x OpenClosePosition_Direction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OpenClosePosition_Direction) Descriptor() protoreflect.EnumDescriptor {
	return file_traits_open_close_proto_enumTypes[0].Descriptor()
}

func (OpenClosePosition_Direction) Type() protoreflect.EnumType {
	return &file_traits_open_close_proto_enumTypes[0]
}

func (x OpenClosePosition_Direction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OpenClosePosition_Direction.Descriptor instead.
func (OpenClosePosition_Direction) EnumDescriptor() ([]byte, []int) {
	return file_traits_open_close_proto_rawDescGZIP(), []int{1, 0}
}

// Resistance defines types of resistance an OpenClose device may encounter.
type OpenClosePosition_Resistance int32

const (
	// Resistance is unspecified.
	OpenClosePosition_RESISTANCE_UNSPECIFIED OpenClosePosition_Resistance = 0
	// The device is being held in position.
	// For example if someone is holding open a door, or a window is jammed shut.
	OpenClosePosition_HELD OpenClosePosition_Resistance = 1
	// The devices motion is reduced. For example if a garage door can't open fully due to a blockage.
	OpenClosePosition_REDUCED_MOTION OpenClosePosition_Resistance = 2
	// The device is being slow to respond to changes in opening. For example if a window has a rusty hinge.
	OpenClosePosition_SLOW OpenClosePosition_Resistance = 3
)

// Enum value maps for OpenClosePosition_Resistance.
var (
	OpenClosePosition_Resistance_name = map[int32]string{
		0: "RESISTANCE_UNSPECIFIED",
		1: "HELD",
		2: "REDUCED_MOTION",
		3: "SLOW",
	}
	OpenClosePosition_Resistance_value = map[string]int32{
		"RESISTANCE_UNSPECIFIED": 0,
		"HELD":                   1,
		"REDUCED_MOTION":         2,
		"SLOW":                   3,
	}
)

func (x OpenClosePosition_Resistance) Enum() *OpenClosePosition_Resistance {
	p := new(OpenClosePosition_Resistance)
	*p = x
	return p
}

func (x OpenClosePosition_Resistance) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OpenClosePosition_Resistance) Descriptor() protoreflect.EnumDescriptor {
	return file_traits_open_close_proto_enumTypes[1].Descriptor()
}

func (OpenClosePosition_Resistance) Type() protoreflect.EnumType {
	return &file_traits_open_close_proto_enumTypes[1]
}

func (x OpenClosePosition_Resistance) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OpenClosePosition_Resistance.Descriptor instead.
func (OpenClosePosition_Resistance) EnumDescriptor() ([]byte, []int) {
	return file_traits_open_close_proto_rawDescGZIP(), []int{1, 1}
}

// All open/closable elements for the device
type OpenClosePositions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The state of each of the devices open-able elements. Most devices will only have a single value here as they can
	// only be opened from a single direction.
	States []*OpenClosePosition `protobuf:"bytes,1,rep,name=states,proto3" json:"states,omitempty"`
	// A preset set of positions (or mode) for the device.
	// For example 'auto' or 'night mode'.
	// During writes the preset takes precedence over the positions in states.
	// During read the device may report either or both the preset and states values.
	Preset        *OpenClosePositions_Preset `protobuf:"bytes,2,opt,name=preset,proto3" json:"preset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenClosePositions) Reset() {
	*x = OpenClosePositions{}
	mi := &file_traits_open_close_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenClosePositions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenClosePositions) ProtoMessage() {}

func (x *OpenClosePositions) ProtoReflect() protoreflect.Message {
	mi := &file_traits_open_close_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenClosePositions.ProtoReflect.Descriptor instead.
func (*OpenClosePositions) Descriptor() ([]byte, []int) {
	return file_traits_open_close_proto_rawDescGZIP(), []int{0}
}

func (x *OpenClosePositions) GetStates() []*OpenClosePosition {
	if x != nil {
		return x.States
	}
	return nil
}

func (x *OpenClosePositions) GetPreset() *OpenClosePositions_Preset {
	if x != nil {
		return x.Preset
	}
	return nil
}

// Defines the position of one open close element for the device
type OpenClosePosition struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Open percent describes how open the device is in the specified direction.
	// [0-100] where 0 is fully closed and 100 is fully open.
	OpenPercent float32 `protobuf:"fixed32,1,opt,name=open_percent,json=openPercent,proto3" json:"open_percent,omitempty"`
	// How the open percent changes or should change over time. On write, only duration should be set.
	OpenPercentTween *types.Tween `protobuf:"bytes,2,opt,name=open_percent_tween,json=openPercentTween,proto3" json:"open_percent_tween,omitempty"`
	// Read-only, the target open_percent after a transition
	TargetOpenPercent float32 `protobuf:"fixed32,3,opt,name=target_open_percent,json=targetOpenPercent,proto3" json:"target_open_percent,omitempty"`
	// Optional direction for devices that support multiple open/close directions
	Direction OpenClosePosition_Direction `protobuf:"varint,4,opt,name=direction,proto3,enum=smartcore.traits.OpenClosePosition_Direction" json:"direction,omitempty"`
	// Resistance reports if there is any resistance preventing the position from being fully achieved.
	// For example if a door is being held open, or a window is jammed closed.
	//
	// If more than one resistance applies choose the resistance value with the smaller ordinal, for example choose
	// REDUCED_MOTION over SLOW if both apply.
	Resistance    OpenClosePosition_Resistance `protobuf:"varint,5,opt,name=resistance,proto3,enum=smartcore.traits.OpenClosePosition_Resistance" json:"resistance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenClosePosition) Reset() {
	*x = OpenClosePosition{}
	mi := &file_traits_open_close_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenClosePosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenClosePosition) ProtoMessage() {}

func (x *OpenClosePosition) ProtoReflect() protoreflect.Message {
	mi := &file_traits_open_close_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenClosePosition.ProtoReflect.Descriptor instead.
func (*OpenClosePosition) Descriptor() ([]byte, []int) {
	return file_traits_open_close_proto_rawDescGZIP(), []int{1}
}

func (x *OpenClosePosition) GetOpenPercent() float32 {
	if x != nil {
		return x.OpenPercent
	}
	return 0
}

func (x *OpenClosePosition) GetOpenPercentTween() *types.Tween {
	if x != nil {
		return x.OpenPercentTween
	}
	return nil
}

func (x *OpenClosePosition) GetTargetOpenPercent() float32 {
	if x != nil {
		return x.TargetOpenPercent
	}
	return 0
}

func (x *OpenClosePosition) GetDirection() OpenClosePosition_Direction {
	if x != nil {
		return x.Direction
	}
	return OpenClosePosition_DIRECTION_UNSPECIFIED
}

func (x *OpenClosePosition) GetResistance() OpenClosePosition_Resistance {
	if x != nil {
		return x.Resistance
	}
	return OpenClosePosition_RESISTANCE_UNSPECIFIED
}

// PositionsSupport describes the capabilities of devices implementing this trait
type PositionsSupport struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// How a named device supports read/write/pull apis
	ResourceSupport *types.ResourceSupport `protobuf:"bytes,1,opt,name=resource_support,json=resourceSupport,proto3" json:"resource_support,omitempty"`
	// Define how the value for open percent behave. The bounds for these attributes will be absent and always in the range
	// [0-100] to represent a percentage.
	// Discreet devices, those that only support fully closed or fully open (i.e. a contact closure) should report a step of 100.
	OpenPercentAttributes *types.FloatAttributes `protobuf:"bytes,2,opt,name=open_percent_attributes,json=openPercentAttributes,proto3" json:"open_percent_attributes,omitempty"`
	// The supported directions for the device. If none then assume only a single direction is supported
	Directions []OpenClosePosition_Direction `protobuf:"varint,3,rep,packed,name=directions,proto3,enum=smartcore.traits.OpenClosePosition_Direction" json:"directions,omitempty"`
	// Does the device support the Stop method
	SupportsStop bool `protobuf:"varint,4,opt,name=supports_stop,json=supportsStop,proto3" json:"supports_stop,omitempty"`
	// A description of the supported presets, none means no presets
	Presets       []*OpenClosePositions_Preset `protobuf:"bytes,5,rep,name=presets,proto3" json:"presets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PositionsSupport) Reset() {
	*x = PositionsSupport{}
	mi := &file_traits_open_close_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PositionsSupport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositionsSupport) ProtoMessage() {}

func (x *PositionsSupport) ProtoReflect() protoreflect.Message {
	mi := &file_traits_open_close_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PositionsSupport.ProtoReflect.Descriptor instead.
func (*PositionsSupport) Descriptor() ([]byte, []int) {
	return file_traits_open_close_proto_rawDescGZIP(), []int{2}
}

func (x *PositionsSupport) GetResourceSupport() *types.ResourceSupport {
	if x != nil {
		return x.ResourceSupport
	}
	return nil
}

func (x *PositionsSupport) GetOpenPercentAttributes() *types.FloatAttributes {
	if x != nil {
		return x.OpenPercentAttributes
	}
	return nil
}

func (x *PositionsSupport) GetDirections() []OpenClosePosition_Direction {
	if x != nil {
		return x.Directions
	}
	return nil
}

func (x *PositionsSupport) GetSupportsStop() bool {
	if x != nil {
		return x.SupportsStop
	}
	return false
}

func (x *PositionsSupport) GetPresets() []*OpenClosePositions_Preset {
	if x != nil {
		return x.Presets
	}
	return nil
}

type GetOpenClosePositionsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the device to get the state for
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The state fields to fetch
	ReadMask      *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=read_mask,json=readMask,proto3" json:"read_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOpenClosePositionsRequest) Reset() {
	*x = GetOpenClosePositionsRequest{}
	mi := &file_traits_open_close_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOpenClosePositionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOpenClosePositionsRequest) ProtoMessage() {}

func (x *GetOpenClosePositionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_traits_open_close_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOpenClosePositionsRequest.ProtoReflect.Descriptor instead.
func (*GetOpenClosePositionsRequest) Descriptor() ([]byte, []int) {
	return file_traits_open_close_proto_rawDescGZIP(), []int{3}
}

func (x *GetOpenClosePositionsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetOpenClosePositionsRequest) GetReadMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.ReadMask
	}
	return nil
}

type UpdateOpenClosePositionsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// the name of the device to update the states for
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// target states for each directional element of the device. If you don't want to change an open direction don't
	// include it in the states list.
	States *OpenClosePositions `protobuf:"bytes,2,opt,name=states,proto3" json:"states,omitempty"`
	// indicate whether the state change is a delta or absolute value
	Delta bool `protobuf:"varint,3,opt,name=delta,proto3" json:"delta,omitempty"`
	// The state fields to update
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,4,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOpenClosePositionsRequest) Reset() {
	*x = UpdateOpenClosePositionsRequest{}
	mi := &file_traits_open_close_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOpenClosePositionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOpenClosePositionsRequest) ProtoMessage() {}

func (x *UpdateOpenClosePositionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_traits_open_close_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOpenClosePositionsRequest.ProtoReflect.Descriptor instead.
func (*UpdateOpenClosePositionsRequest) Descriptor() ([]byte, []int) {
	return file_traits_open_close_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateOpenClosePositionsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateOpenClosePositionsRequest) GetStates() *OpenClosePositions {
	if x != nil {
		return x.States
	}
	return nil
}

func (x *UpdateOpenClosePositionsRequest) GetDelta() bool {
	if x != nil {
		return x.Delta
	}
	return false
}

func (x *UpdateOpenClosePositionsRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

type StopOpenCloseRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// the name of the device to stop
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopOpenCloseRequest) Reset() {
	*x = StopOpenCloseRequest{}
	mi := &file_traits_open_close_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopOpenCloseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopOpenCloseRequest) ProtoMessage() {}

func (x *StopOpenCloseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_traits_open_close_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopOpenCloseRequest.ProtoReflect.Descriptor instead.
func (*StopOpenCloseRequest) Descriptor() ([]byte, []int) {
	return file_traits_open_close_proto_rawDescGZIP(), []int{5}
}

func (x *StopOpenCloseRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Request to begin a subscription for open close state changes
type PullOpenClosePositionsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the device we want events from
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Indicate whether we want to be notified of values while tweening or not. The device may ignore this depending on
	// capabilities
	ExcludeTweening bool `protobuf:"varint,2,opt,name=exclude_tweening,json=excludeTweening,proto3" json:"exclude_tweening,omitempty"`
	// The state fields to fetch
	ReadMask *fieldmaskpb.FieldMask `protobuf:"bytes,3,opt,name=read_mask,json=readMask,proto3" json:"read_mask,omitempty"`
	// When true the device will only send changes to the resource value.
	// The default behaviour is to send the current value immediately followed by any updates as they happen.
	UpdatesOnly   bool `protobuf:"varint,4,opt,name=updates_only,json=updatesOnly,proto3" json:"updates_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullOpenClosePositionsRequest) Reset() {
	*x = PullOpenClosePositionsRequest{}
	mi := &file_traits_open_close_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullOpenClosePositionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullOpenClosePositionsRequest) ProtoMessage() {}

func (x *PullOpenClosePositionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_traits_open_close_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullOpenClosePositionsRequest.ProtoReflect.Descriptor instead.
func (*PullOpenClosePositionsRequest) Descriptor() ([]byte, []int) {
	return file_traits_open_close_proto_rawDescGZIP(), []int{6}
}

func (x *PullOpenClosePositionsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PullOpenClosePositionsRequest) GetExcludeTweening() bool {
	if x != nil {
		return x.ExcludeTweening
	}
	return false
}

func (x *PullOpenClosePositionsRequest) GetReadMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.ReadMask
	}
	return nil
}

func (x *PullOpenClosePositionsRequest) GetUpdatesOnly() bool {
	if x != nil {
		return x.UpdatesOnly
	}
	return false
}

// A response as part of the stream of changes to the range value
type PullOpenClosePositionsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The list of changes
	Changes       []*PullOpenClosePositionsResponse_Change `protobuf:"bytes,1,rep,name=changes,proto3" json:"changes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullOpenClosePositionsResponse) Reset() {
	*x = PullOpenClosePositionsResponse{}
	mi := &file_traits_open_close_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullOpenClosePositionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullOpenClosePositionsResponse) ProtoMessage() {}

func (x *PullOpenClosePositionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_traits_open_close_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullOpenClosePositionsResponse.ProtoReflect.Descriptor instead.
func (*PullOpenClosePositionsResponse) Descriptor() ([]byte, []int) {
	return file_traits_open_close_proto_rawDescGZIP(), []int{7}
}

func (x *PullOpenClosePositionsResponse) GetChanges() []*PullOpenClosePositionsResponse_Change {
	if x != nil {
		return x.Changes
	}
	return nil
}

type DescribePositionsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the device
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribePositionsRequest) Reset() {
	*x = DescribePositionsRequest{}
	mi := &file_traits_open_close_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribePositionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribePositionsRequest) ProtoMessage() {}

func (x *DescribePositionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_traits_open_close_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribePositionsRequest.ProtoReflect.Descriptor instead.
func (*DescribePositionsRequest) Descriptor() ([]byte, []int) {
	return file_traits_open_close_proto_rawDescGZIP(), []int{8}
}

func (x *DescribePositionsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// A preset position for the device.
type OpenClosePositions_Preset struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The identifying name of the preset.
	// Required.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// A human readable title for the preset
	Title         string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenClosePositions_Preset) Reset() {
	*x = OpenClosePositions_Preset{}
	mi := &file_traits_open_close_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenClosePositions_Preset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenClosePositions_Preset) ProtoMessage() {}

func (x *OpenClosePositions_Preset) ProtoReflect() protoreflect.Message {
	mi := &file_traits_open_close_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenClosePositions_Preset.ProtoReflect.Descriptor instead.
func (*OpenClosePositions_Preset) Descriptor() ([]byte, []int) {
	return file_traits_open_close_proto_rawDescGZIP(), []int{0, 0}
}

func (x *OpenClosePositions_Preset) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OpenClosePositions_Preset) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

// A change to a single devices open close state value
type PullOpenClosePositionsResponse_Change struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name for the device that issued the change
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// when the change occurred
	ChangeTime *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=change_time,json=changeTime,proto3" json:"change_time,omitempty"`
	// The new value for the state
	OpenClosePosition *OpenClosePositions `protobuf:"bytes,3,opt,name=open_close_position,json=openClosePosition,proto3" json:"open_close_position,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PullOpenClosePositionsResponse_Change) Reset() {
	*x = PullOpenClosePositionsResponse_Change{}
	mi := &file_traits_open_close_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullOpenClosePositionsResponse_Change) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullOpenClosePositionsResponse_Change) ProtoMessage() {}

func (x *PullOpenClosePositionsResponse_Change) ProtoReflect() protoreflect.Message {
	mi := &file_traits_open_close_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullOpenClosePositionsResponse_Change.ProtoReflect.Descriptor instead.
func (*PullOpenClosePositionsResponse_Change) Descriptor() ([]byte, []int) {
	return file_traits_open_close_proto_rawDescGZIP(), []int{7, 0}
}

func (x *PullOpenClosePositionsResponse_Change) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PullOpenClosePositionsResponse_Change) GetChangeTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ChangeTime
	}
	return nil
}

func (x *PullOpenClosePositionsResponse_Change) GetOpenClosePosition() *OpenClosePositions {
	if x != nil {
		return x.OpenClosePosition
	}
	return nil
}

var File_traits_open_close_proto protoreflect.FileDescriptor

const file_traits_open_close_proto_rawDesc = "" +
	"\n" +
	"\x17traits/open_close.proto\x12\x10smartcore.traits\x1a google/protobuf/field_mask.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x10types/info.proto\x1a\x12types/number.proto\x1a\x11types/tween.proto\"\xca\x01\n" +
	"\x12OpenClosePositions\x12;\n" +
	"\x06states\x18\x01 \x03(\v2#.smartcore.traits.OpenClosePositionR\x06states\x12C\n" +
	"\x06preset\x18\x02 \x01(\v2+.smartcore.traits.OpenClosePositions.PresetR\x06preset\x1a2\n" +
	"\x06Preset\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\"\xfb\x03\n" +
	"\x11OpenClosePosition\x12!\n" +
	"\fopen_percent\x18\x01 \x01(\x02R\vopenPercent\x12D\n" +
	"\x12open_percent_tween\x18\x02 \x01(\v2\x16.smartcore.types.TweenR\x10openPercentTween\x12.\n" +
	"\x13target_open_percent\x18\x03 \x01(\x02R\x11targetOpenPercent\x12K\n" +
	"\tdirection\x18\x04 \x01(\x0e2-.smartcore.traits.OpenClosePosition.DirectionR\tdirection\x12N\n" +
	"\n" +
	"resistance\x18\x05 \x01(\x0e2..smartcore.traits.OpenClosePosition.ResistanceR\n" +
	"resistance\"^\n" +
	"\tDirection\x12\x19\n" +
	"\x15DIRECTION_UNSPECIFIED\x10\x00\x12\x06\n" +
	"\x02UP\x10\x01\x12\b\n" +
	"\x04DOWN\x10\x02\x12\b\n" +
	"\x04LEFT\x10\x03\x12\t\n" +
	"\x05RIGHT\x10\x04\x12\x06\n" +
	"\x02IN\x10\x05\x12\a\n" +
	"\x03OUT\x10\x06\"P\n" +
	"\n" +
	"Resistance\x12\x1a\n" +
	"\x16RESISTANCE_UNSPECIFIED\x10\x00\x12\b\n" +
	"\x04HELD\x10\x01\x12\x12\n" +
	"\x0eREDUCED_MOTION\x10\x02\x12\b\n" +
	"\x04SLOW\x10\x03\"\xf4\x02\n" +
	"\x10PositionsSupport\x12K\n" +
	"\x10resource_support\x18\x01 \x01(\v2 .smartcore.types.ResourceSupportR\x0fresourceSupport\x12X\n" +
	"\x17open_percent_attributes\x18\x02 \x01(\v2 .smartcore.types.FloatAttributesR\x15openPercentAttributes\x12M\n" +
	"\n" +
	"directions\x18\x03 \x03(\x0e2-.smartcore.traits.OpenClosePosition.DirectionR\n" +
	"directions\x12#\n" +
	"\rsupports_stop\x18\x04 \x01(\bR\fsupportsStop\x12E\n" +
	"\apresets\x18\x05 \x03(\v2+.smartcore.traits.OpenClosePositions.PresetR\apresets\"k\n" +
	"\x1cGetOpenClosePositionsRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x127\n" +
	"\tread_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\breadMask\"\xc6\x01\n" +
	"\x1fUpdateOpenClosePositionsRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12<\n" +
	"\x06states\x18\x02 \x01(\v2$.smartcore.traits.OpenClosePositionsR\x06states\x12\x14\n" +
	"\x05delta\x18\x03 \x01(\bR\x05delta\x12;\n" +
	"\vupdate_mask\x18\x04 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\"*\n" +
	"\x14StopOpenCloseRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\xba\x01\n" +
	"\x1dPullOpenClosePositionsRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12)\n" +
	"\x10exclude_tweening\x18\x02 \x01(\bR\x0fexcludeTweening\x127\n" +
	"\tread_mask\x18\x03 \x01(\v2\x1a.google.protobuf.FieldMaskR\breadMask\x12!\n" +
	"\fupdates_only\x18\x04 \x01(\bR\vupdatesOnly\"\xa5\x02\n" +
	"\x1ePullOpenClosePositionsResponse\x12Q\n" +
	"\achanges\x18\x01 \x03(\v27.smartcore.traits.PullOpenClosePositionsResponse.ChangeR\achanges\x1a\xaf\x01\n" +
	"\x06Change\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12;\n" +
	"\vchange_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"changeTime\x12T\n" +
	"\x13open_close_position\x18\x03 \x01(\v2$.smartcore.traits.OpenClosePositionsR\x11openClosePosition\".\n" +
	"\x18DescribePositionsRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name2\xac\x03\n" +
	"\fOpenCloseApi\x12d\n" +
	"\fGetPositions\x12..smartcore.traits.GetOpenClosePositionsRequest\x1a$.smartcore.traits.OpenClosePositions\x12j\n" +
	"\x0fUpdatePositions\x121.smartcore.traits.UpdateOpenClosePositionsRequest\x1a$.smartcore.traits.OpenClosePositions\x12T\n" +
	"\x04Stop\x12&.smartcore.traits.StopOpenCloseRequest\x1a$.smartcore.traits.OpenClosePositions\x12t\n" +
	"\rPullPositions\x12/.smartcore.traits.PullOpenClosePositionsRequest\x1a0.smartcore.traits.PullOpenClosePositionsResponse0\x012t\n" +
	"\rOpenCloseInfo\x12c\n" +
	"\x11DescribePositions\x12*.smartcore.traits.DescribePositionsRequest\x1a\".smartcore.traits.PositionsSupportBy\n" +
	"\x14dev.smartcore.traitsB\x0eOpenCloseProtoP\x01Z)github.com/smart-core-os/sc-api/go/traits\xaa\x02\x10Smartcore.Traits\xca\x02\x10Smartcore\\Traitsb\x06proto3"

var (
	file_traits_open_close_proto_rawDescOnce sync.Once
	file_traits_open_close_proto_rawDescData []byte
)

func file_traits_open_close_proto_rawDescGZIP() []byte {
	file_traits_open_close_proto_rawDescOnce.Do(func() {
		file_traits_open_close_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_traits_open_close_proto_rawDesc), len(file_traits_open_close_proto_rawDesc)))
	})
	return file_traits_open_close_proto_rawDescData
}

var file_traits_open_close_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_traits_open_close_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_traits_open_close_proto_goTypes = []any{
	(OpenClosePosition_Direction)(0),              // 0: smartcore.traits.OpenClosePosition.Direction
	(OpenClosePosition_Resistance)(0),             // 1: smartcore.traits.OpenClosePosition.Resistance
	(*OpenClosePositions)(nil),                    // 2: smartcore.traits.OpenClosePositions
	(*OpenClosePosition)(nil),                     // 3: smartcore.traits.OpenClosePosition
	(*PositionsSupport)(nil),                      // 4: smartcore.traits.PositionsSupport
	(*GetOpenClosePositionsRequest)(nil),          // 5: smartcore.traits.GetOpenClosePositionsRequest
	(*UpdateOpenClosePositionsRequest)(nil),       // 6: smartcore.traits.UpdateOpenClosePositionsRequest
	(*StopOpenCloseRequest)(nil),                  // 7: smartcore.traits.StopOpenCloseRequest
	(*PullOpenClosePositionsRequest)(nil),         // 8: smartcore.traits.PullOpenClosePositionsRequest
	(*PullOpenClosePositionsResponse)(nil),        // 9: smartcore.traits.PullOpenClosePositionsResponse
	(*DescribePositionsRequest)(nil),              // 10: smartcore.traits.DescribePositionsRequest
	(*OpenClosePositions_Preset)(nil),             // 11: smartcore.traits.OpenClosePositions.Preset
	(*PullOpenClosePositionsResponse_Change)(nil), // 12: smartcore.traits.PullOpenClosePositionsResponse.Change
	(*types.Tween)(nil),                           // 13: smartcore.types.Tween
	(*types.ResourceSupport)(nil),                 // 14: smartcore.types.ResourceSupport
	(*types.FloatAttributes)(nil),                 // 15: smartcore.types.FloatAttributes
	(*fieldmaskpb.FieldMask)(nil),                 // 16: google.protobuf.FieldMask
	(*timestamppb.Timestamp)(nil),                 // 17: google.protobuf.Timestamp
}
var file_traits_open_close_proto_depIdxs = []int32{
	3,  // 0: smartcore.traits.OpenClosePositions.states:type_name -> smartcore.traits.OpenClosePosition
	11, // 1: smartcore.traits.OpenClosePositions.preset:type_name -> smartcore.traits.OpenClosePositions.Preset
	13, // 2: smartcore.traits.OpenClosePosition.open_percent_tween:type_name -> smartcore.types.Tween
	0,  // 3: smartcore.traits.OpenClosePosition.direction:type_name -> smartcore.traits.OpenClosePosition.Direction
	1,  // 4: smartcore.traits.OpenClosePosition.resistance:type_name -> smartcore.traits.OpenClosePosition.Resistance
	14, // 5: smartcore.traits.PositionsSupport.resource_support:type_name -> smartcore.types.ResourceSupport
	15, // 6: smartcore.traits.PositionsSupport.open_percent_attributes:type_name -> smartcore.types.FloatAttributes
	0,  // 7: smartcore.traits.PositionsSupport.directions:type_name -> smartcore.traits.OpenClosePosition.Direction
	11, // 8: smartcore.traits.PositionsSupport.presets:type_name -> smartcore.traits.OpenClosePositions.Preset
	16, // 9: smartcore.traits.GetOpenClosePositionsRequest.read_mask:type_name -> google.protobuf.FieldMask
	2,  // 10: smartcore.traits.UpdateOpenClosePositionsRequest.states:type_name -> smartcore.traits.OpenClosePositions
	16, // 11: smartcore.traits.UpdateOpenClosePositionsRequest.update_mask:type_name -> google.protobuf.FieldMask
	16, // 12: smartcore.traits.PullOpenClosePositionsRequest.read_mask:type_name -> google.protobuf.FieldMask
	12, // 13: smartcore.traits.PullOpenClosePositionsResponse.changes:type_name -> smartcore.traits.PullOpenClosePositionsResponse.Change
	17, // 14: smartcore.traits.PullOpenClosePositionsResponse.Change.change_time:type_name -> google.protobuf.Timestamp
	2,  // 15: smartcore.traits.PullOpenClosePositionsResponse.Change.open_close_position:type_name -> smartcore.traits.OpenClosePositions
	5,  // 16: smartcore.traits.OpenCloseApi.GetPositions:input_type -> smartcore.traits.GetOpenClosePositionsRequest
	6,  // 17: smartcore.traits.OpenCloseApi.UpdatePositions:input_type -> smartcore.traits.UpdateOpenClosePositionsRequest
	7,  // 18: smartcore.traits.OpenCloseApi.Stop:input_type -> smartcore.traits.StopOpenCloseRequest
	8,  // 19: smartcore.traits.OpenCloseApi.PullPositions:input_type -> smartcore.traits.PullOpenClosePositionsRequest
	10, // 20: smartcore.traits.OpenCloseInfo.DescribePositions:input_type -> smartcore.traits.DescribePositionsRequest
	2,  // 21: smartcore.traits.OpenCloseApi.GetPositions:output_type -> smartcore.traits.OpenClosePositions
	2,  // 22: smartcore.traits.OpenCloseApi.UpdatePositions:output_type -> smartcore.traits.OpenClosePositions
	2,  // 23: smartcore.traits.OpenCloseApi.Stop:output_type -> smartcore.traits.OpenClosePositions
	9,  // 24: smartcore.traits.OpenCloseApi.PullPositions:output_type -> smartcore.traits.PullOpenClosePositionsResponse
	4,  // 25: smartcore.traits.OpenCloseInfo.DescribePositions:output_type -> smartcore.traits.PositionsSupport
	21, // [21:26] is the sub-list for method output_type
	16, // [16:21] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_traits_open_close_proto_init() }
func file_traits_open_close_proto_init() {
	if File_traits_open_close_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_traits_open_close_proto_rawDesc), len(file_traits_open_close_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_traits_open_close_proto_goTypes,
		DependencyIndexes: file_traits_open_close_proto_depIdxs,
		EnumInfos:         file_traits_open_close_proto_enumTypes,
		MessageInfos:      file_traits_open_close_proto_msgTypes,
	}.Build()
	File_traits_open_close_proto = out.File
	file_traits_open_close_proto_goTypes = nil
	file_traits_open_close_proto_depIdxs = nil
}
