# This driver is still in active development, so there is some code that isn't
# used yet but we expect it to be in future.
# Remove this after https://github.com/smart-core-os/sc-bos/pull/539 is merged.
checks = ["inherit", "-U1000"]