/**
 * @fileoverview gRPC-Web generated client stub for smartcore.bos.waste.v1
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v2.0.2
// 	protoc              v6.32.1
// source: smartcore/bos/waste/v1/waste.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');


var google_protobuf_field_mask_pb = require('google-protobuf/google/protobuf/field_mask_pb.js')

var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js')

var types_change_pb = require('@smart-core-os/sc-api-grpc-web/types/change_pb.js')

var types_info_pb = require('@smart-core-os/sc-api-grpc-web/types/info_pb.js')

var types_time_period_pb = require('@smart-core-os/sc-api-grpc-web/types/time/period_pb.js')
const proto = {};
proto.smartcore = {};
proto.smartcore.bos = {};
proto.smartcore.bos.waste = {};
proto.smartcore.bos.waste.v1 = require('./waste_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.smartcore.bos.waste.v1.WasteApiClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.smartcore.bos.waste.v1.WasteApiPromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.smartcore.bos.waste.v1.ListWasteRecordsRequest,
 *   !proto.smartcore.bos.waste.v1.ListWasteRecordsResponse>}
 */
const methodDescriptor_WasteApi_ListWasteRecords = new grpc.web.MethodDescriptor(
  '/smartcore.bos.waste.v1.WasteApi/ListWasteRecords',
  grpc.web.MethodType.UNARY,
  proto.smartcore.bos.waste.v1.ListWasteRecordsRequest,
  proto.smartcore.bos.waste.v1.ListWasteRecordsResponse,
  /**
   * @param {!proto.smartcore.bos.waste.v1.ListWasteRecordsRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.smartcore.bos.waste.v1.ListWasteRecordsResponse.deserializeBinary
);


/**
 * @param {!proto.smartcore.bos.waste.v1.ListWasteRecordsRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.smartcore.bos.waste.v1.ListWasteRecordsResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.smartcore.bos.waste.v1.ListWasteRecordsResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.smartcore.bos.waste.v1.WasteApiClient.prototype.listWasteRecords =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/smartcore.bos.waste.v1.WasteApi/ListWasteRecords',
      request,
      metadata || {},
      methodDescriptor_WasteApi_ListWasteRecords,
      callback);
};


/**
 * @param {!proto.smartcore.bos.waste.v1.ListWasteRecordsRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.smartcore.bos.waste.v1.ListWasteRecordsResponse>}
 *     Promise that resolves to the response
 */
proto.smartcore.bos.waste.v1.WasteApiPromiseClient.prototype.listWasteRecords =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/smartcore.bos.waste.v1.WasteApi/ListWasteRecords',
      request,
      metadata || {},
      methodDescriptor_WasteApi_ListWasteRecords);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.smartcore.bos.waste.v1.PullWasteRecordsRequest,
 *   !proto.smartcore.bos.waste.v1.PullWasteRecordsResponse>}
 */
const methodDescriptor_WasteApi_PullWasteRecords = new grpc.web.MethodDescriptor(
  '/smartcore.bos.waste.v1.WasteApi/PullWasteRecords',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.smartcore.bos.waste.v1.PullWasteRecordsRequest,
  proto.smartcore.bos.waste.v1.PullWasteRecordsResponse,
  /**
   * @param {!proto.smartcore.bos.waste.v1.PullWasteRecordsRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.smartcore.bos.waste.v1.PullWasteRecordsResponse.deserializeBinary
);


/**
 * @param {!proto.smartcore.bos.waste.v1.PullWasteRecordsRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.smartcore.bos.waste.v1.PullWasteRecordsResponse>}
 *     The XHR Node Readable Stream
 */
proto.smartcore.bos.waste.v1.WasteApiClient.prototype.pullWasteRecords =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/smartcore.bos.waste.v1.WasteApi/PullWasteRecords',
      request,
      metadata || {},
      methodDescriptor_WasteApi_PullWasteRecords);
};


/**
 * @param {!proto.smartcore.bos.waste.v1.PullWasteRecordsRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.smartcore.bos.waste.v1.PullWasteRecordsResponse>}
 *     The XHR Node Readable Stream
 */
proto.smartcore.bos.waste.v1.WasteApiPromiseClient.prototype.pullWasteRecords =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/smartcore.bos.waste.v1.WasteApi/PullWasteRecords',
      request,
      metadata || {},
      methodDescriptor_WasteApi_PullWasteRecords);
};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.smartcore.bos.waste.v1.WasteInfoClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.smartcore.bos.waste.v1.WasteInfoPromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.smartcore.bos.waste.v1.DescribeWasteRecordRequest,
 *   !proto.smartcore.bos.waste.v1.WasteRecordSupport>}
 */
const methodDescriptor_WasteInfo_DescribeWasteRecord = new grpc.web.MethodDescriptor(
  '/smartcore.bos.waste.v1.WasteInfo/DescribeWasteRecord',
  grpc.web.MethodType.UNARY,
  proto.smartcore.bos.waste.v1.DescribeWasteRecordRequest,
  proto.smartcore.bos.waste.v1.WasteRecordSupport,
  /**
   * @param {!proto.smartcore.bos.waste.v1.DescribeWasteRecordRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.smartcore.bos.waste.v1.WasteRecordSupport.deserializeBinary
);


/**
 * @param {!proto.smartcore.bos.waste.v1.DescribeWasteRecordRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.smartcore.bos.waste.v1.WasteRecordSupport)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.smartcore.bos.waste.v1.WasteRecordSupport>|undefined}
 *     The XHR Node Readable Stream
 */
proto.smartcore.bos.waste.v1.WasteInfoClient.prototype.describeWasteRecord =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/smartcore.bos.waste.v1.WasteInfo/DescribeWasteRecord',
      request,
      metadata || {},
      methodDescriptor_WasteInfo_DescribeWasteRecord,
      callback);
};


/**
 * @param {!proto.smartcore.bos.waste.v1.DescribeWasteRecordRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.smartcore.bos.waste.v1.WasteRecordSupport>}
 *     Promise that resolves to the response
 */
proto.smartcore.bos.waste.v1.WasteInfoPromiseClient.prototype.describeWasteRecord =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/smartcore.bos.waste.v1.WasteInfo/DescribeWasteRecord',
      request,
      metadata || {},
      methodDescriptor_WasteInfo_DescribeWasteRecord);
};


module.exports = proto.smartcore.bos.waste.v1;

