// Code generated by protoc-gen-wrapper. DO NOT EDIT.

package metadatapb

import (
	wrap "github.com/smart-core-os/sc-bos/pkg/wrap"
	grpc "google.golang.org/grpc"
)

// WrapApi	adapts a MetadataApiServer	and presents it as a MetadataApiClient
func WrapApi(server MetadataApiServer) *ApiWrapper {
	conn := wrap.ServerToClient(MetadataApi_ServiceDesc, server)
	client := NewMetadataApiClient(conn)
	return &ApiWrapper{
		MetadataApiClient: client,
		server:            server,
		conn:              conn,
		desc:              MetadataApi_ServiceDesc,
	}
}

type ApiWrapper struct {
	MetadataApiClient

	server MetadataApiServer
	conn   grpc.ClientConnInterface
	desc   grpc.ServiceDesc
}

// UnwrapServer returns the underlying server instance.
func (w *ApiWrapper) UnwrapServer() MetadataApiServer {
	return w.server
}

// Unwrap implements wrap.Unwrapper and returns the underlying server instance as an unknown type.
func (w *ApiWrapper) Unwrap() any {
	return w.UnwrapServer()
}

func (w *ApiWrapper) UnwrapService() (grpc.ClientConnInterface, grpc.ServiceDesc) {
	return w.conn, w.desc
}
