// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: smartcore/bos/history/v1/history.proto

package historypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// HistoryRecord is a generic record of a device's state at a point in time.
// Prefer using trait specific record types where possible.
type HistoryRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	CreateTime    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryRecord) Reset() {
	*x = HistoryRecord{}
	mi := &file_smartcore_bos_history_v1_history_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryRecord) ProtoMessage() {}

func (x *HistoryRecord) ProtoReflect() protoreflect.Message {
	mi := &file_smartcore_bos_history_v1_history_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryRecord.ProtoReflect.Descriptor instead.
func (*HistoryRecord) Descriptor() ([]byte, []int) {
	return file_smartcore_bos_history_v1_history_proto_rawDescGZIP(), []int{0}
}

func (x *HistoryRecord) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *HistoryRecord) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *HistoryRecord) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *HistoryRecord) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type CreateHistoryRecordRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The record to create.
	// The id and create_time fields must be absent.
	Record        *HistoryRecord `protobuf:"bytes,2,opt,name=record,proto3" json:"record,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateHistoryRecordRequest) Reset() {
	*x = CreateHistoryRecordRequest{}
	mi := &file_smartcore_bos_history_v1_history_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateHistoryRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHistoryRecordRequest) ProtoMessage() {}

func (x *CreateHistoryRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_smartcore_bos_history_v1_history_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHistoryRecordRequest.ProtoReflect.Descriptor instead.
func (*CreateHistoryRecordRequest) Descriptor() ([]byte, []int) {
	return file_smartcore_bos_history_v1_history_proto_rawDescGZIP(), []int{1}
}

func (x *CreateHistoryRecordRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateHistoryRecordRequest) GetRecord() *HistoryRecord {
	if x != nil {
		return x.Record
	}
	return nil
}

type ListHistoryRecordsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The maximum number of records to return.
	// The service may return fewer than this value.
	// If unspecified, at most 50 items will be returned.
	// The maximum value is 1000; values above 1000 will be coerced to 1000.
	PageSize int32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// A page token, received from a previous `ListHistoryRecords` call.
	// Provide this to retrieve the subsequent page.
	PageToken string `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// Specify the order of the returned records.
	// The default is `create_time asc` - aka oldest record first.
	// The format is `field_name [asc|desc]`, with asc being the default.
	// Only `create_time` is supported.
	OrderBy       string               `protobuf:"bytes,5,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	Query         *HistoryRecord_Query `protobuf:"bytes,4,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListHistoryRecordsRequest) Reset() {
	*x = ListHistoryRecordsRequest{}
	mi := &file_smartcore_bos_history_v1_history_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHistoryRecordsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHistoryRecordsRequest) ProtoMessage() {}

func (x *ListHistoryRecordsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_smartcore_bos_history_v1_history_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHistoryRecordsRequest.ProtoReflect.Descriptor instead.
func (*ListHistoryRecordsRequest) Descriptor() ([]byte, []int) {
	return file_smartcore_bos_history_v1_history_proto_rawDescGZIP(), []int{2}
}

func (x *ListHistoryRecordsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListHistoryRecordsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListHistoryRecordsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListHistoryRecordsRequest) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

func (x *ListHistoryRecordsRequest) GetQuery() *HistoryRecord_Query {
	if x != nil {
		return x.Query
	}
	return nil
}

type ListHistoryRecordsResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Records []*HistoryRecord       `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	// A token, which can be sent as `page_token` to retrieve the next page.
	// If this field is omitted, there are no subsequent pages.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	// If non-zero this is the total number of records matched by the query.
	// This may be an estimate.
	TotalSize     int32 `protobuf:"varint,3,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListHistoryRecordsResponse) Reset() {
	*x = ListHistoryRecordsResponse{}
	mi := &file_smartcore_bos_history_v1_history_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHistoryRecordsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHistoryRecordsResponse) ProtoMessage() {}

func (x *ListHistoryRecordsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_smartcore_bos_history_v1_history_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHistoryRecordsResponse.ProtoReflect.Descriptor instead.
func (*ListHistoryRecordsResponse) Descriptor() ([]byte, []int) {
	return file_smartcore_bos_history_v1_history_proto_rawDescGZIP(), []int{3}
}

func (x *ListHistoryRecordsResponse) GetRecords() []*HistoryRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *ListHistoryRecordsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListHistoryRecordsResponse) GetTotalSize() int32 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

type HistoryRecord_Query struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Source:
	//
	//	*HistoryRecord_Query_SourceEqual
	Source isHistoryRecord_Query_Source `protobuf_oneof:"source"`
	// The bounding records to select: from_record <= record < to_record.
	// ID or create_time (in that order) will be used for result selection.
	FromRecord    *HistoryRecord `protobuf:"bytes,10,opt,name=from_record,json=fromRecord,proto3" json:"from_record,omitempty"`
	ToRecord      *HistoryRecord `protobuf:"bytes,11,opt,name=to_record,json=toRecord,proto3" json:"to_record,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryRecord_Query) Reset() {
	*x = HistoryRecord_Query{}
	mi := &file_smartcore_bos_history_v1_history_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryRecord_Query) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryRecord_Query) ProtoMessage() {}

func (x *HistoryRecord_Query) ProtoReflect() protoreflect.Message {
	mi := &file_smartcore_bos_history_v1_history_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryRecord_Query.ProtoReflect.Descriptor instead.
func (*HistoryRecord_Query) Descriptor() ([]byte, []int) {
	return file_smartcore_bos_history_v1_history_proto_rawDescGZIP(), []int{0, 0}
}

func (x *HistoryRecord_Query) GetSource() isHistoryRecord_Query_Source {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *HistoryRecord_Query) GetSourceEqual() string {
	if x != nil {
		if x, ok := x.Source.(*HistoryRecord_Query_SourceEqual); ok {
			return x.SourceEqual
		}
	}
	return ""
}

func (x *HistoryRecord_Query) GetFromRecord() *HistoryRecord {
	if x != nil {
		return x.FromRecord
	}
	return nil
}

func (x *HistoryRecord_Query) GetToRecord() *HistoryRecord {
	if x != nil {
		return x.ToRecord
	}
	return nil
}

type isHistoryRecord_Query_Source interface {
	isHistoryRecord_Query_Source()
}

type HistoryRecord_Query_SourceEqual struct {
	SourceEqual string `protobuf:"bytes,1,opt,name=source_equal,json=sourceEqual,proto3,oneof"`
}

func (*HistoryRecord_Query_SourceEqual) isHistoryRecord_Query_Source() {}

var File_smartcore_bos_history_v1_history_proto protoreflect.FileDescriptor

const file_smartcore_bos_history_v1_history_proto_rawDesc = "" +
	"\n" +
	"&smartcore/bos/history/v1/history.proto\x12\x18smartcore.bos.history.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd7\x02\n" +
	"\rHistoryRecord\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12;\n" +
	"\vcreate_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\x1a\xc6\x01\n" +
	"\x05Query\x12#\n" +
	"\fsource_equal\x18\x01 \x01(\tH\x00R\vsourceEqual\x12H\n" +
	"\vfrom_record\x18\n" +
	" \x01(\v2'.smartcore.bos.history.v1.HistoryRecordR\n" +
	"fromRecord\x12D\n" +
	"\tto_record\x18\v \x01(\v2'.smartcore.bos.history.v1.HistoryRecordR\btoRecordB\b\n" +
	"\x06source\"q\n" +
	"\x1aCreateHistoryRecordRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12?\n" +
	"\x06record\x18\x02 \x01(\v2'.smartcore.bos.history.v1.HistoryRecordR\x06record\"\xcb\x01\n" +
	"\x19ListHistoryRecordsRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\x12\x19\n" +
	"\border_by\x18\x05 \x01(\tR\aorderBy\x12C\n" +
	"\x05query\x18\x04 \x01(\v2-.smartcore.bos.history.v1.HistoryRecord.QueryR\x05query\"\xa6\x01\n" +
	"\x1aListHistoryRecordsResponse\x12A\n" +
	"\arecords\x18\x01 \x03(\v2'.smartcore.bos.history.v1.HistoryRecordR\arecords\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12\x1d\n" +
	"\n" +
	"total_size\x18\x03 \x01(\x05R\ttotalSize2\x88\x02\n" +
	"\x0fHistoryAdminApi\x12t\n" +
	"\x13CreateHistoryRecord\x124.smartcore.bos.history.v1.CreateHistoryRecordRequest\x1a'.smartcore.bos.history.v1.HistoryRecord\x12\x7f\n" +
	"\x12ListHistoryRecords\x123.smartcore.bos.history.v1.ListHistoryRecordsRequest\x1a4.smartcore.bos.history.v1.ListHistoryRecordsResponseB5Z3github.com/smart-core-os/sc-bos/pkg/proto/historypbb\x06proto3"

var (
	file_smartcore_bos_history_v1_history_proto_rawDescOnce sync.Once
	file_smartcore_bos_history_v1_history_proto_rawDescData []byte
)

func file_smartcore_bos_history_v1_history_proto_rawDescGZIP() []byte {
	file_smartcore_bos_history_v1_history_proto_rawDescOnce.Do(func() {
		file_smartcore_bos_history_v1_history_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_smartcore_bos_history_v1_history_proto_rawDesc), len(file_smartcore_bos_history_v1_history_proto_rawDesc)))
	})
	return file_smartcore_bos_history_v1_history_proto_rawDescData
}

var file_smartcore_bos_history_v1_history_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_smartcore_bos_history_v1_history_proto_goTypes = []any{
	(*HistoryRecord)(nil),              // 0: smartcore.bos.history.v1.HistoryRecord
	(*CreateHistoryRecordRequest)(nil), // 1: smartcore.bos.history.v1.CreateHistoryRecordRequest
	(*ListHistoryRecordsRequest)(nil),  // 2: smartcore.bos.history.v1.ListHistoryRecordsRequest
	(*ListHistoryRecordsResponse)(nil), // 3: smartcore.bos.history.v1.ListHistoryRecordsResponse
	(*HistoryRecord_Query)(nil),        // 4: smartcore.bos.history.v1.HistoryRecord.Query
	(*timestamppb.Timestamp)(nil),      // 5: google.protobuf.Timestamp
}
var file_smartcore_bos_history_v1_history_proto_depIdxs = []int32{
	5, // 0: smartcore.bos.history.v1.HistoryRecord.create_time:type_name -> google.protobuf.Timestamp
	0, // 1: smartcore.bos.history.v1.CreateHistoryRecordRequest.record:type_name -> smartcore.bos.history.v1.HistoryRecord
	4, // 2: smartcore.bos.history.v1.ListHistoryRecordsRequest.query:type_name -> smartcore.bos.history.v1.HistoryRecord.Query
	0, // 3: smartcore.bos.history.v1.ListHistoryRecordsResponse.records:type_name -> smartcore.bos.history.v1.HistoryRecord
	0, // 4: smartcore.bos.history.v1.HistoryRecord.Query.from_record:type_name -> smartcore.bos.history.v1.HistoryRecord
	0, // 5: smartcore.bos.history.v1.HistoryRecord.Query.to_record:type_name -> smartcore.bos.history.v1.HistoryRecord
	1, // 6: smartcore.bos.history.v1.HistoryAdminApi.CreateHistoryRecord:input_type -> smartcore.bos.history.v1.CreateHistoryRecordRequest
	2, // 7: smartcore.bos.history.v1.HistoryAdminApi.ListHistoryRecords:input_type -> smartcore.bos.history.v1.ListHistoryRecordsRequest
	0, // 8: smartcore.bos.history.v1.HistoryAdminApi.CreateHistoryRecord:output_type -> smartcore.bos.history.v1.HistoryRecord
	3, // 9: smartcore.bos.history.v1.HistoryAdminApi.ListHistoryRecords:output_type -> smartcore.bos.history.v1.ListHistoryRecordsResponse
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_smartcore_bos_history_v1_history_proto_init() }
func file_smartcore_bos_history_v1_history_proto_init() {
	if File_smartcore_bos_history_v1_history_proto != nil {
		return
	}
	file_smartcore_bos_history_v1_history_proto_msgTypes[4].OneofWrappers = []any{
		(*HistoryRecord_Query_SourceEqual)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_smartcore_bos_history_v1_history_proto_rawDesc), len(file_smartcore_bos_history_v1_history_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_smartcore_bos_history_v1_history_proto_goTypes,
		DependencyIndexes: file_smartcore_bos_history_v1_history_proto_depIdxs,
		MessageInfos:      file_smartcore_bos_history_v1_history_proto_msgTypes,
	}.Build()
	File_smartcore_bos_history_v1_history_proto = out.File
	file_smartcore_bos_history_v1_history_proto_goTypes = nil
	file_smartcore_bos_history_v1_history_proto_depIdxs = nil
}
