// Code generated by protoc-gen-router. DO NOT EDIT.

package vendingpb

import (
	fmt "fmt"
	router "github.com/smart-core-os/sc-bos/pkg/router"
	grpc "google.golang.org/grpc"
)

// InfoRouter is a VendingInfoServer that allows routing named requests to specific VendingInfoClient
type InfoRouter struct {
	UnimplementedVendingInfoServer

	router.Router
}

// compile time check that we implement the interface we need
var _ VendingInfoServer = (*InfoRouter)(nil)

func NewInfoRouter(opts ...router.Option) *InfoRouter {
	return &InfoRouter{
		Router: router.NewRouter(opts...),
	}
}

// WithVendingInfoClientFactory instructs the router to create a new
// client the first time Get is called for that name.
func WithVendingInfoClientFactory(f func(name string) (VendingInfoClient, error)) router.Option {
	return router.WithFactory(func(name string) (any, error) {
		return f(name)
	})
}

func (r *InfoRouter) Register(server grpc.ServiceRegistrar) {
	RegisterVendingInfoServer(server, r)
}

// Add extends Router.Add to panic if client is not of type VendingInfoClient.
func (r *InfoRouter) Add(name string, client any) any {
	if !r.HoldsType(client) {
		panic(fmt.Sprintf("not correct type: client of type %T is not a VendingInfoClient", client))
	}
	return r.Router.Add(name, client)
}

func (r *InfoRouter) HoldsType(client any) bool {
	_, ok := client.(VendingInfoClient)
	return ok
}

func (r *InfoRouter) AddVendingInfoClient(name string, client VendingInfoClient) VendingInfoClient {
	res := r.Add(name, client)
	if res == nil {
		return nil
	}
	return res.(VendingInfoClient)
}

func (r *InfoRouter) RemoveVendingInfoClient(name string) VendingInfoClient {
	res := r.Remove(name)
	if res == nil {
		return nil
	}
	return res.(VendingInfoClient)
}

func (r *InfoRouter) GetVendingInfoClient(name string) (VendingInfoClient, error) {
	res, err := r.Get(name)
	if err != nil {
		return nil, err
	}
	if res == nil {
		return nil, nil
	}
	return res.(VendingInfoClient), nil
}
