name: Go Security Scan

on:
  push:
    branches:
      - main
    paths:
      - 'go.mod'
      - 'go.sum'
      - 'cmd/**'
      - 'internal/**'
      - 'pkg/**'
      - '.github/**'

  pull_request:
    paths:
      - 'go.mod'
      - 'go.sum'
      - 'cmd/**'
      - 'internal/**'
      - 'pkg/**'
      - '.github/**'

jobs:
  govulncheck_job:
    runs-on: ubuntu-latest
    name: Run govulncheck
    steps:
      - id: govulncheck
        uses: golang/govulncheck-action@v1
        with:
          go-version-input: 1.26
          go-package: ./...
