name: Go Test

on:
  # run tests on any commit that touches Go files on main, or in any PR
  push:
    branches: [ main ]
    paths:
      - 'go.mod'
      - 'go.sum'
      - 'cmd/**'
      - 'internal/**'
      - 'pkg/**'
      - '.github/**'
  pull_request:
    paths:
      - 'go.mod'
      - 'go.sum'
      - 'cmd/**'
      - 'internal/**'
      - 'pkg/**'
      - '.github/**'

jobs:
  test-all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          cache: true
          go-version: '^1.26.x'

      - name: Test (cachable)
        run: go test -skip '_e2e$' ./...

      - name: Test (uncachable)
        run: go test -count=1 -run '_e2e$' ./...

      - name: Test short tests under race detector
        run: go test -short -race ./...
